### ISSUE TITLE
"Run on Device": Error when running games

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#1020]
**Describe the bug**
After running https://sprig.hackclub.com/gallery/FRC_TEAM_2016_Monkey_Madness, it's impossible to run another game
**To Reproduce**
1. 
1. Go to https://sprig.hackclub.com/gallery/FRC_TEAM_2016_Monkey_Madness
2. Click on `Run on Device`
3. The game will be uploaded, click on any button on the console and you will see that nothing happened
4. Go to https://sprig.hackclub.com/share/sgvFk5tv3gQRoEtc5Klu
5. Click on `Run on Device`
6. See that it just keeps loading and nothing happens
(I was recording 15 minutes from the loading button and the hour ticking, until Windows said "An error occurred" and I lost the recording)

cc: @leomcelroy

**Comment by LucasHT22** [comment]
sorry, wdym with "default loading screen"? Press any key to run screen?

**Comment by leomcelroy** [comment]
Yes that screen.

**Comment by LucasHT22** [comment]
> If you cycle the power can you upload a game from the default loading screen?


no, the screen is frozen and the editor just keeps loading, to upload just re-booting

**Comment by LucasHT22** [comment]
wow, interesting

**Comment by leomcelroy** [comment]
Great detective work @snoglobe

**Comment by kognise** [comment]
Yes!
