### ISSUE TITLE
`/share` doesn't recognize logged in account

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#1021]
**Screenshots**
https://cloud-cpxjw5qwj-hack-club-bot.vercel.app/020230505-2038-22.5587033.mp4
(I know, I need to delete and rename some games)

when you enter a link via /share, Sprig doesn't recognize that you are logged in

**Comment by JosiasAurel** [comment]
This does not happen anymore. Please re-open if it does!
