### ISSUE TITLE
A new sprigfuzzy for `/games`

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#1024]
The current version of the test, a.k.a sprigfuzzy, located in the folder [`/test`](https://github.com/hackclub/sprig/blob/main/tests/sprigfuzzy.js) it's outdated, without the test running, we aren't sure if the game will run on the console

**Comment by grymmy** [comment]
Closing as duplicate of https://github.com/hackclub/sprig/issues/1104
