### ISSUE TITLE
Include line and column number for invalid character errors

### ISSUE THREAD

**Issue by SamDev-7** [hackclub/sprig#1040]
Users can choose to add text to their game with `addText`. However, the font has a limited support for special characters. An error will appear when the user tries to character add text with unsupported characters. This change was implemented in (#1030) and can be seen in the [Sprig Engine](https://github.com/hackclub/sprig-engine/blob/e5e3c0c179ddee62b78d74753d836ab550b84b6e/src/base/text.ts#L17).

The example of the current error looks as follows.
```
Error: Character $ is not in the font. It will be rendered incorrectly.
```

As a quality of life change, it would help to include information about where the invalid character is.

An example of how this could look:
```
Error: Character $ is not in the font. It will be rendered incorrectly.
    at <game>:39:16
```

**Comment by grymmy** [comment]
@SamDev-7 I am sorry for the slow response on this issue - however, I do not see sufficient information here for this issue to be actionable.  Can you please update the description and title of this issue to be more clear re: exactly what the feature request is - because I read this and while I could jump to conclusions, I'd rather not...

Please assign this back to me once you've added info here to make this actionable...

**Comment by SamDev-7** [comment]
I have updated the description, let me know if further clarification is needed.

**Comment by grymmy** [comment]
@leomcelroy please weigh in on your approval/disapproval re: this feature request.  If you approve, do please specify the full set of characters you feel we should support.  If you do not approve, plz close w/ commentary.

**Comment by leomcelroy** [comment]
These characters are supported

 !\"#%&\'()*+,./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\^_-`abcdefghijklmnopqrstuvwxyz|~¦§¨©¬®¯°±´¶·¸ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ÙÚÛÜÝÞßàáâãäåæçèéêëìíîïñòóôõö÷ùúûüýþÿĀāĂăĄąĆćĊċČčĎĐđĒēĖėĘęĚěĞğĠġĦħĪīĮįİıŃńŇňŌōŒœŞşŨũŪūŮůŲųŴŵŶŷŸǍǎǏǐǑǒǓǔˆˇ˘˙˚˛˜˝ẀẁẂẃẄẅỲỳ†‡•…‰⁄™∂∅∏∑−√∞∫≈≠≤≥◊
 
 I do support improving the error messages to include error location when possible.
