### ISSUE TITLE
Weird behavior in line error highlighting when scrolled offscreen

### ISSUE THREAD

**Issue by SamDev-7** [hackclub/sprig#1041]
**Describe the bug**
After receiving an error with the corresponding line gutter highlighted (introduced in #954), scrolling the page causing the highlighted gutter to be off-screen causes it to disappear and occasionally appears in the wrong locations.

**To Reproduce**
1. Go to the web editor
2. Create an error where it will highlight the line. Have a lot of lines for scrolling. ([Example](https://sprig.hackclub.com/share/TVsZz7f12utPDsoDbFCl))
3. Scroll far enough such that the highlighted line gutter is far off-screen.
4. Observe the line gutter highlight.

**Expected behavior**
For the highlight to persist after scrolling it off-screen.

**Actual behavior**  
The highlight is gone from its original place and may appear in random, incorrect, lines.

**Screenshots**
![image](https://github.com/hackclub/sprig/assets/66446458/d457fa58-dc2d-4d2e-9382-a20d2fa508f5)

**Comment by grymmy** [comment]
@SamDev-7 do you plan on taking action re: this issue?

**Comment by SamDev-7** [comment]
Apologies, something got in the way and I never got back to this. I'll be looking over it today to see if I can attempt a fix.

**Comment by SamDev-7** [comment]
I was unable to find a solution to make this work.
