### ISSUE TITLE
sprig workshop overhaul: create intro slides

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#1075]
what is sprig (an editor, device and games)
show intro video
why bother? -- learn JS via making, you will be making actual games that can be played, will learn how to make PRs.
will step you through from hacking to creating your own.

**Comment by LucasHT22** [comment]
I know that Belle and Thomas already made slides about the Sprig, it might be interesting to consult them

**Comment by karamassie** [comment]
yes! have reached out to all that have made sprig workshops for slides. ty!!

**Comment by grymmy** [comment]
@karamassie I am closing this as I believe this work was already completed - please reopen if you feel this was closed in error.
