### ISSUE TITLE
old video linked in the getting started game

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#1076]
https://workshops.hackclub.com/sprig_first_game/ links the old video which shows the old editor

this is the correct video : https://www.youtube.com/watch?v=ZOPYB6dw4Os

**Comment by LucasHT22** [comment]
hmmm imo the correct video doesn't cover everything the old video covers

**Comment by leomcelroy** [comment]
Yeah there needs to be an updated video for this if we are going to change the link.

https://www.youtube.com/watch?v=1UTLS4aO9bQ

**Comment by grymmy** [comment]
@LucasHT22 can you please look at this and close this if it has already been fixed?

**Comment by LucasHT22** [comment]
@grymmy We still don't have a video that covers what the old one covers, so it's not finished

**Comment by grymmy** [comment]
@karamassie do we expect this video to be created?

**Comment by karamassie** [comment]
@LucasHT22  what content is missing in the new video, pls?

**Comment by karamassie** [comment]
this is actually fixed!
