### ISSUE TITLE
sprig workshop overhaul : revise and improve the first tutorial game (for first session)

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#1077]
let's look at https://sprig.hackclub.com/gallery/getting_started

and improve on it.

**Comment by LucasHT22** [comment]
Improve in what sense?

**Comment by karamassie** [comment]
we've had feedback that a couple of spots are unclear, and we're making it more interactive.

**Comment by LucasHT22** [comment]
interesting!

**Comment by SamDev-7** [comment]
Just to be clear, we're working on improving https://sprig.hackclub.com/gallery/getting_started

**Comment by LucasHT22** [comment]
so I think it's better rename the title and fix Kara's description
