### ISSUE TITLE
Run Sprig games in a web worker

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#1091]
Currently, Sprig games run in the main thread, meaning any freezes occurring in the Sprig game (like an infinite while loop) will freeze up the editor as well; this could be fixed by moving all game logic to a web worker that's terminated & recreated on each run.

I came across this issue this week when working on a game & having my editor freeze & delete my work after every unsuccessful run.

**Comment by recursiveforte** [comment]
I can work on this if I have bandwidth later this week.

**Comment by grymmy** [comment]
@recursiveforte do you still wish to look into this?  Seems like a reasonable feature

**Comment by grymmy** [comment]
I firmly believe this should be considered a bug and not a feature request, and thus am reclassifying it as such.  The editor shouldn't break when someone accidently writes an infinite loop.

**Comment by leomcelroy** [comment]
I reiterate that I strongly recommend implementing infinite loop checking with ast analysis as described by Replit. I've implemented the web-worker alternative and it brings a large number of challenges and alternative issues.

**Comment by grymmy** [comment]
> I reiterate that I strongly recommend implementing infinite loop checking with ast analysis as described by Replit. I've implemented the web-worker alternative and it brings a large number of challenges and alternative issues. 

This will be taken into consideration

**Comment by JosiasAurel** [comment]
The editor will now report potential infinite loops to prevent freezing since #1413
