### ISSUE TITLE
CI - Sprig games JSON is not validated before deploy

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#1102]
the JSON manifest for Sprig games is not validated in the CI step, meaning it's possible for an invalid JSON file to be pushed, making  /gallery and /gallery/* throw 500.
we experienced this today with the JSON file fixed by commit `572959c`

**Comment by grymmy** [comment]
@DevIos01 hrm would the plagiarism detector blow up in this scenario, and thus cover this angle?  If so, please close this issue with a comment as such.  If not, please assign back to me w/ why not

**Comment by leomcelroy** [comment]
This should also be addressed by relying on in file metadata which obsolesces this file.

**Comment by recursiveforte** [comment]
Deploying with Vercel fails if metadata isn’t correct, fixing this issue.
