### ISSUE TITLE
Weird behavior of example game.

### ISSUE THREAD

**Issue by V205Arduino** [hackclub/sprig#1106]
**Describe the bug**
The getting started game does this:

<img width="462" alt="image" src="https://github.com/hackclub/sprig/assets/138826219/e86f967b-07ef-4553-89e7-0caea47cf2d3">

Is it supposed to do that?

**To Reproduce**

1. Go to Sprig editor
2. Enter:
3. const player = "p";
const box = "b";
const goal = "g";
const wall = "w";

setLegend(
    [
        player,
        bitmap`
................
................
................
.......0........
.....00.000.....
....0.....00....
....0.0.0..0....
....0......0....
....0......0....
....00....0.....
......00000.....
......0...0.....
....000...000...
................
................
................`
    ],
    [
        box,
        bitmap`
................
................
................
...888888888....
...8...8...8....
...8...8...8....
...8...8...8....
...8...8...8....
...888888888....
...8...8...8....
...8...8...8....
...888888888....
................
................
................
................`
    ],
    [
        goal,
        bitmap`
................
................
................
....444444......
...44....44.....
...4......4.....
...4.......4....
...4.......4....
...4.......4....
...44......4....
....4......4....
....44....44....
.....444444.....
................
................
................`
    ],
    [
        wall,
        bitmap`
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000`
    ]
);

let level = 0;
const levels = [
    map`
p.w.
.bwg
....
....`,
    map`
p.w.
.bwg
....
..bg`
];

const currentLevel = levels[level];
setMap(currentLevel);

onInput("w", () => {
    getFirst(player).y -= 1;
});

onInput("s", () => {
    getFirst(player).y += 1;
});

onInput("a", () => {
    getFirst(player).x -= 1;
});

onInput("d", () => {
    getFirst(player).x += 1;
});

onInput("j", () => {
    const currentLevel = levels[level];
    if (currentLevel !== undefined) setMap(currentLevel);
});

setSolids([player, box, wall]);

setPushables({
    [player]: [box]
});

afterInput(() => {
    const numberCovered = tilesWith(goal, box).length;
    const targetNumber = tilesWith(goal).length;

    if (numberCovered === targetNumber) {
        // increase the current level number
        level = level + 1;

        const currentLevel = levels[level];

        // make sure the level exists and if so set the map
        if (currentLevel !== undefined) {
            setMap(currentLevel);
        } else {
            addText("you win!", { y: 4, color: color`3` });
        }
    }
});

4. Run code.
5. Go to level 2.
6. See error

**Expected behavior**
I though the purple box should vanish…..

**Actual behavior**  
Clear and concise description of what actually happens

**Screenshots**

**Comment by V205Arduino** [comment]
https://workshops.hackclub.com/sprig_first_game/

**Comment by leomcelroy** [comment]
What issue are you pointing out? That the level is unsolvable at that point? If so that is just part of the puzzle. It's very common to get stuck there.

**Comment by V205Arduino** [comment]
Oh. I thought that was a bug.
Sorry.
Is there a complete guide sheet?
