### ISSUE TITLE
Make tutorial pane resizable

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#1109]
the tutorial pane should be resizable (like the game window is) so that it can be expanded for easier reading when needed. this is especially important for tutorials/jams where you need to read through lots of code or text.

**Comment by leomcelroy** [comment]
I've been helping some classrooms use sprig and found that many people struggled and complained about closing the help panel repeatedly. I'm thinking of going back to placing the toolkit/tutorials underneath the game window. So as you read through you can run the game. The other issue they were facing with closing the panel and switching tabs was losing the scroll location. If the help window is tied to the right hand panel it will be resizable in the x dimension. We could also make it adjustable on y. 

Want to help implement this change? We could pair on it.

**Comment by recursiveforte** [comment]
I could work on implementing this!

**Comment by polypixeldev** [comment]
I'm going through Part 2 of the Sprig Batch Jam and also having issues with having to open and close the help panel and losing my scroll location in the tutorial when I go to look at the help docs. Has any progress/decisions been made on this issue? I'm happy to help with implementing this.

**Comment by grymmy** [comment]
@polypixeldev assigned this over to you as you stated you could help work on it
