### ISSUE TITLE
Investigate why Vercel doesn't auto-deploy every PR

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#1145]
CC @grymmy

**Comment by LucasHT22** [comment]
Thanks for the info! We want to allow preview auto-deployment to all PRs without needing authorization from a Hack Club Vercel member

**Comment by grymmy** [comment]
What specific environment variables in Sprig would potentially be exposed, and how severe of an emergency would it be if that happened?

**Comment by LucasHT22** [comment]
> Seems like the Firebase DB token, the SendGrid key, and the ReCaptcha key https://github.com/hackclub/sprig/blob/b8d2b655bd88e066d6041b900c222a0cd59f202c/src/env.d.ts

Confirmed from vercel

**Comment by grymmy** [comment]
If we had a separate firebase creds used specifically for prs that wouldn't effect real prod if it was leaked, and if we banned ppl abusing prs in a way, would there be any problem?

**Comment by grymmy** [comment]
> I'm still not sure there's a way to turn off the Vercel approval requirement

Why?

**Comment by grymmy** [comment]
Relevant:
<img width="853" alt="Screenshot 2023-09-22 at 8 56 42 AM" src="https://github.com/hackclub/sprig/assets/43505167/8dabfb2d-3a48-4493-a72a-67781c1d253b">

**Comment by grymmy** [comment]
Also very relevant - Vercel does allow for overriding environment variables per-environment, so we could provision a new database cred solely for using for preview deploys which would not have any serious security/privacy concerns...  The other two environment variables we could just set to null - for instance, leaving email sending non-functional is probably a good idea in preview anyway <img width="1011" alt="Screenshot 2023-09-22 at 9 04 16 AM" src="https://github.com/hackclub/sprig/assets/43505167/7a07f089-c0d5-4265-986f-4ac7709a8360">

**Comment by LucasHT22** [comment]
> Also very relevant - Vercel does allow for overriding environment variables per-environment, so we could provision a new database cred solely for using for preview deploys which would not have any serious security/privacy concerns... The other two environment variables we could just set to null - for instance, leaving email sending non-functional is probably a good idea in preview anyway <img alt="Screenshot 2023-09-22 at 9 04 16 AM" width="1011" src="https://user-images.githubusercontent.com/43505167/269946091-7a07f089-c0d5-4265-986f-4ac7709a8360.png">

And then select specific branches when testing something w/email? Sounds ok

**Comment by JosiasAurel** [comment]
new credentials have been provisioned for the preview environment
