### ISSUE TITLE
Stop running button

### ISSUE THREAD

**Issue by jakjakob** [hackclub/sprig#1146]
would be useful to not having it running all the time while coding

**Comment by Tiger-The-Cat** [comment]
Thanks for pointing this out! I didn't notice this until now

**Comment by grymmy** [comment]
@leomcelroy do you approve this feature?  Can you specify how it should work and look like?

**Comment by leomcelroy** [comment]
I do approve this feature. But by replacing the play button it requires you to hit the button twice to rerun your game. Does that also mean that shift+enter now toggles between playing and pausing the game loop. I would instead suggest adding the pause button next to mute.

**Comment by grymmy** [comment]
Thanks @leomcelroy - plz feel free to assign me issues relating to feature requests after you approve them, I will triage them for implementation.
