### ISSUE TITLE
Sprig Dodge

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#1152]
The sprig dodge tutorial doesn't run.

**Comment by LucasHT22** [comment]
It was done on purpose so that it would not be possible to execute it the first time, the Sprig_dodge was made with a difficult level bigger than getting_started.
The message "This code has intentional errors." on header aims to signal that. On Step 3 is the step that you solve the bug:)

**Comment by LucasHT22** [comment]
This thread from 30 Nov. 2022 shows the process of creating this error:
https://hackclub.slack.com/archives/C046PEVB9AS/p1669854679481749?thread_ts=1669824177.343889&cid=C046PEVB9AS

**Comment by grymmy** [comment]
Closing this per @LucasHT22 's commentary.
