### ISSUE TITLE
Write script to automate plagiarism / copy detection

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1177]
A script should be written (in python, or bash) to surface overlap between submitted app source code and the contents of the gallery. The acceptable amount of overlap should be configurable (default to 50%), and the diff should NOT factor in bitmap/binary data (to avoid people gaming by just changing map/sprite content).  It should return process code 0 if there was no overlapping documents found.  It should return process code 1 if there was an overlap, and output the list of most-similar apps in the gallery to stdout.

**Comment by grymmy** [comment]
It should also remove all unnecessary whitespace from all documents being diffed, I guess...

**Comment by grymmy** [comment]
Pretty sure we should just build our own solution, this is ezpz - @DevIos01 do your magic

**Comment by DevIos01** [comment]
At end we decide to use compare50 , which is now implement on https://github.com/hackclub/sprig/pull/1285 , will rebase it so there is no 10000+ commit on history and moving forward will work on local testing before workflow ;)

here a example test : https://github.com/DevIos01/sprig/pull/56

example code compare being flagged:
![image](https://github.com/hackclub/sprig/assets/34939959/9417e832-bfdb-4dc1-8f5f-67f5b7ff6095)

**Comment by DevIos01** [comment]
Thanks again @ajs256 @Tiger-The-Cat for the suggestion with Compare50, I have decided to use that at the end and now it's completed and merged at https://github.com/hackclub/sprig/pull/1285

It was both annoying and fun at the same time while getting this alive ;)
![8ad7e27c04f68d43526032f33100f0c1](https://github.com/hackclub/sprig/assets/34939959/74886826-a1ea-430e-8d0f-e6c3732536c8)
