### ISSUE TITLE
Confusing error + page freezing "Level must be rect"

### ISSUE THREAD

**Issue by zachlatta** [hackclub/sprig#1194]
**Describe the bug**

**_Two bugs_**

_First bug:_

When helping someone on their game, we got the error `Level must be rect.`. After much searching, we discovered that a character was accidentally deleted from a `bitmap` declaration.

This error message is confusing because it was a `bitmap` declaration that was wrong, not a `map` declaration.

_Second bug:_

Opening the bitmap that is missing a character in the pixel editor freezes the webpage.

**To Reproduce**

1. Go to https://sprig.hackclub.com/share/CdUtqTkENBsCgrwABkWk
2. Try running the game
3. See the error `Level must be rect.`. Note that this is a confusing error, and that the line numbers aren't helpful / are wrong. The actual error is on line 347 of the code.
4. Go to line 347 and click `bitmap` to open the sprite editor. Note that your browser is now frozen and the tab crashes.

**Screenshots**

<img width="529" alt="Screenshot 2023-10-23 at 6 10 46 PM" src="https://github.com/hackclub/sprig/assets/992248/a2b7866e-ca50-40d3-ba95-592a20d4b0a7">

**Comment by grymmy** [comment]
It may be this is related to #1091 ?
