### ISSUE TITLE
Tutorial in editor doesn't follow theme (dark mode)

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/sprig#1204]
**Describe the bug**
On the tutorial panel in the Sprig editor, if you have dark theme enabled the background will still be white and in light mode. The help tab on the same panel does switch to dark mode.

**To Reproduce**
1. Go to the Sprig gallery and enter a tutorial
2. Switch to dark mode
3. See that the tutorial panel stays on light theme

**Expected behavior**
I expected the tutorial panel to switch to dark theme.

**Actual behavior**  
The tutorial panel stays on light theme.
**Screenshots**
![image](https://github.com/hackclub/sprig/assets/79737178/4c1a8acd-9643-460b-b144-f4db6ea7daca)

**Comment by LucasHT22** [comment]
cc @JosiasAurel (?)

**Comment by JosiasAurel** [comment]
This is unintended. I'll try to reproduce asap

**Comment by grymmy** [comment]
@polypixeldev thank you for the excellently-described issue report.
