### ISSUE TITLE
ERROR displays in bottom right of Sprikipedia main page

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1206]
**Describe the bug**
There is a red error message that displays when rendering the sprikipedia main page.

**To Reproduce**
1. Navigate to sprikipedia main page

**Expected behavior**
The page renders cleanly with no error messages.

**Actual behavior**  
A red error message is visible on the bottom right.

**Screenshots**
<img width="945" alt="Screenshot 2023-11-02 at 9 52 39 AM" src="https://github.com/hackclub/sprig/assets/43505167/8687ed58-6bbb-4a3a-becf-317038c44b3a">

**Comment by LucasHT22** [comment]
This is recaptcha, I'll work to not appear
![image](https://github.com/hackclub/sprig/assets/88567622/b4fabb54-dfbb-4a99-ac4b-6a3c87c2a3af)
