### ISSUE TITLE
NavBar not consistent across entirety of Sprikipedia

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1209]
**Describe the bug**
Suggest maintaining the navbar experience across the entire Sprikipedia subsite

**To Reproduce**
1. Navigate to main sprikipedia page.
2. Click on any of the working links to subpages.

**Expected behavior**
Consistent navbar experience across the entire flow of pages.

**Actual behavior**  
There is a distinct and different navbar experience once you click into one of the sublinks.

**Screenshots**
![Screenshot 2023-11-02 at 10 34 14 AM](https://github.com/hackclub/sprig/assets/43505167/29243a44-c67a-4f52-9b19-4c2bcc121c47)
vs
![Screenshot 2023-11-02 at 10 38 48 AM](https://github.com/hackclub/sprig/assets/43505167/73d75a62-ae81-481c-97af-df68902dcc17)

**Comment by LucasHT22** [comment]
In my opinion, it is consistent, all subpages have the same navbar, only the home page changes because the structure is different from the subpages
