### ISSUE TITLE
Add slack channel information to the main README

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1223]
Please add relevant Hack Club slack info to the main readme to direct Sprigsters to the channels they want to find on Slack.  This was reported as a bit of a macro-issue over at https://github.com/hackclub/infra/issues/23.

**Comment by grymmy** [comment]
@LucasHT22 can u please crank this one out?

**Comment by LucasHT22** [comment]
Sure, will work on it on the weekend
