### ISSUE TITLE
Game saves seem to be intermittently not working

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/sprig#1225]
**Describe the bug**
On November 6th, I opened the Sprig editor to work on my game, and learned that I had lost about 10 minutes of work from the prior day. I thought this was just a one-off oopsie and it didn't take long to write again, so I ignored it. However, today I opened up Sprig and discovered that I had somehow lost about 30 minutes of work from a couple days ago.

**To Reproduce**
Don't know how to reproduce unfortunately. On the 7th, I also went to work on my game, but it loaded the code from the 6th fine without issue.

**Expected behavior**
I expected all my code to save correctly when the header bar says that it was saved.

**Actual behavior**  
Saving seems to intermittently not work correctly.

**Screenshots**
N/A

**Comment by polypixeldev** [comment]
It seems like this is a regression of #919

**Comment by grymmy** [comment]
@polypixeldev can you please give a specific time where you believe data was lost?  I am afraid this issue is non-actionable without at least something specific to investigate.  Please assign this issue back to me when you've provided something investigable.

**Comment by polypixeldev** [comment]
I've looked into this a little more and I can confirm that this is a regression of #919 - doesn't load correctly on Firefox when the tab is restored, but a full refresh fixes it. No issue on a different browser as well. Would it make more sense to reopen #919 for this @grymmy ?

**Comment by grymmy** [comment]
@polypixeldev yes please reopen that old issue (citing this one), and close this one, if the context in that thread is superior to this one.  Thank you for investigating this @polypixeldev.

**Comment by polypixeldev** [comment]
I don't think I have perms to reopen the issue, but I added a comment

**Comment by grymmy** [comment]
Thank you @polypixeldev.  Closing this issue.
