### ISSUE TITLE
Feature request review of Sprikipedia

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1246]
Leo,

Lucas has been working hard on his personal Sprikipedia project - it is currently not linked to the main page (i.e. not live) but if you could please provide some feedback to him re: this, and also approve this from a feature request perspective, I am sure Lucas would appreciate it.  It is mainly informational & accessibility-focused, so I doubt this is a controversial one...

Apologies if this discussion has already been had, but would like to ensure we stick w/ process re: features...

Regards,
Graham

**Comment by leomcelroy** [comment]
Very supportive of Sprikipedia. Where is it previewed now and what's included in it?

**Comment by LucasHT22** [comment]
it's live in https://sprig.hackclub.com/sprikipedia, everything about Sprig will be included, from tutorials to who is/how to get involved in Sprig:)

**Comment by grymmy** [comment]
Closing this issue as the goal was to get @leomcelroy 's blessing and feedback on sprikipedia which it seems has been accomplished.
