### ISSUE TITLE
Display warning confirmation when autosaving on a new browser

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1247]
I propose the new feature:

1. When we send a signal to save off data, we additionally include some ID that is tied to the browser (or session, or whatever makes sense to use).
2. When saving, check to see if the previous save used the same ID.  If it is, save as normal.  If not, display a popup on the client asking the user to confirm they want to potentially overwrite their previous changes.

**Comment by grymmy** [comment]
@leomcelroy there have been multiple reports of data loss due to this sort of scenario.  Please approve/disapprove, or decide on a better/different approach to solve this issue, and assign back to me (or close this, if you find that more appropriate)

**Comment by grymmy** [comment]
@leomcelroy ping on this

**Comment by leomcelroy** [comment]
This seems reasonable. Agree the overriding issue should be addressed.
