### ISSUE TITLE
Autosave does not save as expected when losing network connectivity and then regaining it

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1253]
**Describe the bug**
The editor does not gracefully handle saving data when resuming network connectivity.

**To Reproduce**
1. Open an existing game from Your Games in the editor.
2. Add one space, forcing an auto-save - observe save be successful
3. Disconnect your network connection (turn off wifi, for instance)
4. Add one space.  Observe a failure to save.
5. Resume your network connection (turn on wifi).

**Expected behavior**
The new space should be successfully saved shortly after resuming network connectivity.

**Actual behavior**  
"Error saving" popup repeatedly flashes and never saves successfully (even after a full minute or two from what I've observed - until you make another change).

**Screenshots**

https://github.com/hackclub/sprig/assets/43505167/84d29503-fd75-4b9f-add6-979d81d1a91b

**Comment by JosiasAurel** [comment]
fixed since #1255
