### ISSUE TITLE
Support improved debugging capabilities in web editor

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1270]
![image](https://github.com/hackclub/sprig/assets/109123711/8da55f82-7eb2-451b-b4f7-0461ea3f62b5)

the blot editor hosts a much more sophisticated debugging system, where lines with errors are shown and the specific error is pointed to. the Current sprig debugging systems lacks the sophisticated features that make the blot editor so much more useful for debugging.

**Comment by grymmy** [comment]
@Sheepy3 please make this more specific on what exact use cases are superior on blot and missing on Sprig.  The sprig editor does show specific lines w/ errors along with error details.

**Comment by grymmy** [comment]
This gives important context https://docs.google.com/document/d/1AE6xumn45Jv4P7mg_klcPw_zMs9iLsTS5iE17ozvizw/edit

**Comment by grymmy** [comment]
it seems to me that the "big feature" here is just support for a debug console

**Comment by leomcelroy** [comment]
I think the first big thing to address here is improved error messaging.

Error messages should

- have line numbers which are highlighted
- include easily understandable messages when possible
- point to the row as depicted in the screenshot

**Comment by snoglobe** [comment]
splitting into new issues - #1651 and #1652.
