### ISSUE TITLE
Infinite loop detection

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1271]
The sprig editor is not aware of when a user creates an infinite loop, which causes the editor to crash. the editor should display a warning or error if the user creates an infinite loop capable of crashing the editor.

**Comment by grymmy** [comment]
Closing this as duplicate of https://github.com/hackclub/sprig/issues/1091 - also I am not sure how feasible it would be to actually detect infinite loops without potential false-positives
