### ISSUE TITLE
Make the gallery search not case sensitive

### ISSUE THREAD

**Issue by blockishbear166** [hackclub/sprig#1306]
Hey guys! I just wanted to ask if you could make the search bar in the gallery not case sensitive, i think this is just a small quality of life change and i would greatly appreciate it. Thanks!

**Comment by grymmy** [comment]
I am not able to reproduce this - I believe @JosiasAurel fixed this recently.
<img width="639" alt="Screenshot 2023-12-22 at 11 31 03 AM" src="https://github.com/hackclub/sprig/assets/43505167/755663d0-b916-4b02-a55f-c6e0887392f9">
