### ISSUE TITLE
use trie-based search in the sprig gallery

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/sprig#1310]
The sprig gallery currently has to compare every search query against every game which is very inefficient. 
A trie-based approach to search will be vastly more efficient than comparing against every game entry.

**Comment by BrightTheBackpack** [comment]
I can try on work on this. Would this require creating a trie and putting all the games in it everytime it loads? Or is there a way to store it as a trie in like a global file?

**Comment by grymmy** [comment]
@BrightTheBackpack it makes sense to precompute the trie on startup/load and keep a singleton reference to it long-term in memory

**Comment by grymmy** [comment]
@BrightTheBackpack suggest using a standard/flexible open-source implementation instead of rolling your own - there's quite a few out there

**Comment by BrightTheBackpack** [comment]
It's gonna be a little while till I can work on this, me and my family are out on vacation

**Comment by JosiasAurel** [comment]
@BrightTheBackpack are you still up to tackle this issue?

**Comment by BrightTheBackpack** [comment]
I'm a lite busy right now. If you guys aren't on any hurry i can tackle it in a few weeks. Otherwise, you guys can start if you want

**Comment by grymmy** [comment]
I doubt we are doing this.  Closing.
