### ISSUE TITLE
Replace Metadata.JSON with metadata embedded directly into gamefiles

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1322]
Currently, it is required of reviewers to update [metadata.json](https://github.com/hackclub/sprig/blob/main/games/metadata.json) in order to add metadata to new sprig games. Not only does this add extra work to see a game in the gallery, it also creates multiple sources of metadata, when we already collect some metadata from the top of every game file.

It would be best to instead require games to include all their metadata at the top of the gamefile, so that there is a single source of truth, as well as allowing games to be seen in the gallery through the vercel deployment.

**Comment by grymmy** [comment]
Agreed - some quick and dirty shell scripting could be useful to insert the data currently tracked in the metadata.json file into all of the existing game files.

**Comment by grymmy** [comment]
@LucasHT22 be aware

**Comment by LucasHT22** [comment]
There was plans simillar with the old header @title: & @author:

**Comment by GalaxyGamingBoy** [comment]
Updated all games, per issue.
See PR: #1334

**Comment by JosiasAurel** [comment]
#1334 has been merged
