### ISSUE TITLE
Replace CoreAudio with a cross platform audio API

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1324]
Currently, spade PC builds builds are dependent on CoreAudio to emulate sound, which is an API exclusive to MacOS. This limits testing of audio to Apple computers, when windows & linux-based machines should also be capable of testing spade audio.

**Comment by grymmy** [comment]
@Sheepy3 copy/pasted to https://github.com/hackclub/spade/issues/30 to keep things organized, this belongs over there
