### ISSUE TITLE
Extend gallery interface to filter by multiple tag criteria simultaneously

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1330]
Right now the UI limits one to a single tag to filter by.  Propose ability to filter by multiple tag criteria to narrow down games to your preferences.  In concert with #1329 this will result in a far better user experience.

**Comment by grymmy** [comment]
@leomcelroy plz review and approve, or close w/ comment if you do not support this feature

**Comment by leomcelroy** [comment]
I support it. Don't have strong opinions around which tags but definitely keep something like "good for beginners"
