### ISSUE TITLE
improve search and filtering

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/sprig#1331]
the entire search and filtering experience needs some improvements. 
search queries, filter tags and sorting are all inconsistent with one another

consider integrating #1330 if approved too

**Comment by grymmy** [comment]
This is specifically one thing that happens as a result:
<img width="512" alt="Screenshot 2023-12-22 at 10 56 25 AM" src="https://github.com/hackclub/sprig/assets/43505167/efbe4daf-8785-4781-a813-108e51cfdcc0">
<img width="512" alt="Screenshot 2023-12-22 at 10 55 51 AM" src="https://github.com/hackclub/sprig/assets/43505167/ffed257c-e33e-4ddc-b3bf-58899f3a026a">
