### ISSUE TITLE
Gallery Tags isn't filtering games

### ISSUE THREAD

**Issue by revaga** [hackclub/sprig#1352]
**Describe the bug**
If a tag is chosen, the Sprig Gallery doesn't show any games. It only shows games if a tag is chosen and something is typed in search bar.

**To Reproduce**
1. Go to Gallery
2. Choose on a tag from the drop-down menu 

**Expected behavior**
The games in the gallery should sort based on tag chosen.

**Actual behavior**  
No games show up if a tag is chosen. If a tag is chosen and a word is typed into search bar, then a game shows up

**Screenshots**
![image](https://github.com/hackclub/sprig/assets/58123400/84a66825-267a-4f7d-a6b8-96c227b7cc29)

![image](https://github.com/hackclub/sprig/assets/58123400/49737c06-05f3-4209-a7af-12a8e35ae1d8)

**Comment by JosiasAurel** [comment]
@revaga this no longer happens after the PR merge today
