### ISSUE TITLE
Show warning if game upload takes too long

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/sprig#1356]
Sometimes when uploading a game to a Sprig, the upload process will hang and never complete. Usually reconnecting the Sprig and reloading the page will fix this. It would be helpful if after about 30 seconds a warning was shown to the user, saying that the upload seems to have failed and that they should reconnect their Sprig and reload the page.

**Comment by JosiasAurel** [comment]
this might be a relevant piece of code to look into [upload.ts#l41](https://github.com/hackclub/sprig/blob/01ff1b77e9099e7085631c3ae1ea7414c2490b3c/src/lib/upload.ts#L41)

**Comment by grymmy** [comment]
@leomcelroy plz review this feature request and approve/deny

**Comment by leomcelroy** [comment]
Approved! As described sounds good.

- after 30 seconds show pop up modal suggesting closing and restarting the upload process.
