### ISSUE TITLE
confirmation email on sprig request form

### ISSUE THREAD

**Issue by jakjakob** [hackclub/sprig#1376]
self describing

-why?

simply to be sure to not misspell the email (and so that in that case I could reach out to someone)
especially important in case of delays etc. (why didn't I get an email - didi I maybe misspell something?)

things to include after form: you will shortly receive a confirmation email, if not please reach out on slack hq channel (for example)

**Comment by jakjakob** [comment]
useful informations/implementation ideas: 

https://support.airtable.com/docs/when-a-form-is-submitted-trigger
https://support.airtable.com/docs/send-an-email-action

**Comment by grymmy** [comment]
@Sheepy3 this seems like a very reasonable ask and can avoid confusion in the sprig/case awarding flow, we should probably just bang this out

**Comment by Sheepy3** [comment]
I agree that this would probably solve some worries people have

**Comment by Sheepy3** [comment]
setup this automation! it also allows you to confirm your address
