### ISSUE TITLE
Gallery Image Mixup, Non New Games Have 'New' Tag

### ISSUE THREAD

**Issue by Omay238** [hackclub/sprig#1396]
**Describe the bug**
Both happen in the gallery. Sometimes, games will have the wrong image, and it seems that the games at the top of the list always have the 'new' banner thing. I suspect the image issue is caused by some optimization somewhere, and the 'new' banner issue is probably because it's designed to work with sorting by date, and also it's designed to work with all games (none filtered out)

**To Reproduce**
1. Go to Gallery
2. Search for something (I searched for all of my games)
3. See items with 'new' banner on the top
4. Scroll down, see items with wrong image

**Expected behavior**
Only new games have the new banner, games have the image that is assigned to them, not the image assigned to others.

**Actual behavior**  
Any games at the top after searching have the 'new' banner, and images sometimes show up above the wrong games.

**Screenshots**

<img width="453" alt="Screenshot 2024-01-17 at 4 19 59 PM" src="https://github.com/hackclub/sprig/assets/70179858/6a2002b7-9c9c-41bf-b8b1-1b006b0b89e5">

**Comment by Omay238** [comment]
Expected screen
<img width="453" alt="Screenshot 2024-01-17 at 4 28 57 PM" src="https://github.com/hackclub/sprig/assets/70179858/319b1ff4-b243-47a1-a3ad-37d13739e1cb">

**Comment by JosiasAurel** [comment]
the filtering issue is fixed since #1400 
however I'm unable to reproduce the scenario where the images are incorrectly placed

**Comment by JosiasAurel** [comment]
> Expected screen <img alt="Screenshot 2024-01-17 at 4 28 57 PM" width="453" src="https://private-user-images.githubusercontent.com/70179858/297548543-319b1ff4-b243-47a1-a3ad-37d13739e1cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjgzNzMsIm5iZiI6MTcwNTY2ODA3MywicGF0aCI6Ii83MDE3OTg1OC8yOTc1NDg1NDMtMzE5YjFmZjQtYjI0My00N2ExLWEzYWQtMzdkMTM3MzllMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyNDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYzcwZWViNDc1MDFlM2UyNjRkNGVkNTRjM2E5ZDY1NjA2NDEzZjY2YTBiMGI1NzFhMTFkMDllZGIxYTFhOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vNv3OgeRilCfW0UwRGyn9D1S9hh9RwrxVQ_xxU34PCM">

where did you get this expected screen btw?

**Comment by Omay238** [comment]
> however I'm unable to reproduce the scenario where the images are incorrectly placed
you have to type fast and scroll down fast. then the wrong images are used.

https://github.com/hackclub/sprig/assets/70179858/3f119310-46c7-4c32-a623-64d681c2901a

> where did you get this expected screen btw?
i did the typing/scrolling slowly to get the right images, then used inspect to get rid of the 'new' labels

**Comment by JosiasAurel** [comment]
@Omay238 what browser are you using here?

**Comment by Omay238** [comment]
Arc 1.26.0
