### ISSUE TITLE
Feature request: Button to auto-format code

### ISSUE THREAD

**Issue by zachlatta** [hackclub/sprig#1399]
I'm filing this feature request on behalf of @alimyust who got a Sprig in #1358.

I think this would be a great feature to have in the editor, and I would find this particularly helpful as a mentor at hackathons where attendees who are not consistently indenting their code are running into issues with missing curly braces.

**Comment by leomcelroy** [comment]
I approve of this. May warrant done reorganizing of top bar. For now place it in the dropdown. It should only change whitespace.

**Comment by DevIos01** [comment]
> I approve of this. May warrant done reorganizing of top bar. For now place it in the dropdown. It should only change whitespace.

Hey @leomcelroy,

I made a new PR with the changes / idea implementation of this feature request, but was bit unsure about "It should only change whitespace."

the two try i did when implementing "Just the change on whitespace" lead to two scenarios:

1. every whitespace / line was removed and the output was all the code in line 1 
2. a modified version to keep the code where it was and just remove white-line lead to:
![image](https://github.com/hackclub/sprig/assets/34939959/983447cb-299a-47e8-ad4d-0a83a075fef8)

which isn't what we looking for (maybe),  i had chat with @JosiasAurel about this and went with beatify / prettier and use the existing feature that we can expand more in future format style, i just want to check with you if it's what you wanted / happy to do any changes if needed :)

Current formatted code looks like :
![image](https://github.com/hackclub/sprig/assets/34939959/f89556a1-c3a7-49b7-8a40-c60c39b116b7)
