### ISSUE TITLE
"New games" card on main hackclub.com website shows invalid dates (and possibly incorrect games)

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1435]
<img width="1379" alt="Screenshot 2024-02-14 at 2 10 22 PM" src="https://github.com/hackclub/sprig/assets/43505167/f98d787b-4c1b-4dc9-bef1-14bdd7b854f8">

**Comment by JosiasAurel** [comment]
This [line](https://github.com/hackclub/site/blob/a264d8c1939f043eed34cc6f52d82bb3b8416806/components/index/cards/sprig.js#L162) should be updated i suppose. 

The datetime field access should be "addedOn" and not "added on".
