### ISSUE TITLE
Consolidate sprig repos into main repo 

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1436]
as of right now, sprig is split between [spade](https://github.com/hackclub/spade), [sprig](https://github.com/hackclub/sprig), [sprig-hardware](https://github.com/hackclub/sprig-hardware), [sprig engine](https://github.com/hackclub/sprig-engine?tab=readme-ov-file), [sprig order](https://github.com/hackclub/sprig-order), [sprig drop](https://github.com/hackclub/sprig-drop), [sprig holiday case](https://github.com/hackclub/sprig-holiday-case), and [sprig legacy stub.](https://github.com/hackclub/sprig-legacy-stub). it may be worth considering consolidating some or all of these repositories into one.

**Comment by grymmy** [comment]
I think especially spade, sprig, sprig-hardware, and sprig-engine might be good to consolidate together to tighten iteration time and testing across components.  Separation of all of these things in the way we do it now exacts a heavy price on devexp/speed.

**Comment by grymmy** [comment]
tbh though all of the ones listed above seem reasonable

**Comment by leomcelroy** [comment]
Sprig engine is separate because it is published as it's own package.

**Comment by grymmy** [comment]
> Sprig engine is separate because it is published as it's own package.

That's fine it can be incorporated into the same repo and still published

**Comment by grymmy** [comment]
closing this and making an issue specific to sprig-engine
