### ISSUE TITLE
Not all the buttons are visible and can be pressed from mobile

### ISSUE THREAD

**Issue by zachlatta** [hackclub/sprig#1441]
**Describe the bug**

When I open a Sprig game on mobile, I'm unable to view or click all of the buttons needed to play the game.

https://github.com/hackclub/sprig/assets/992248/08dd6d13-5768-4b1c-b7c5-e851d1cd2498

This is on Safari on an iPhone Pro Max 13 running the latest OS.

**Comment by LucasHT22** [comment]
Hmm check if auto-rotate is active:)

**Comment by zachlatta** [comment]
On my phone?

**Comment by LucasHT22** [comment]
> On my phone?

Yes

**Comment by zachlatta** [comment]
Yes, that was it! When I turn on rotation on my phone, it rotates and then it's OK. But I still think this is a bug, because it wasn't obvious to me as the user that this was a problem

**Comment by zachlatta** [comment]
https://github.com/hackclub/sprig/assets/992248/230bce45-09a7-43aa-a726-9a3c3f847110
