### ISSUE TITLE
Provide easier way for people to share game and get back to it to iterate

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#145]
From Maggie's feedback:
 Is there a reason why we can't have permanent URLs? Would make it easier for small bugfixes and if we could customize URLs, it would be easier to share

(and I second... I was confused about where my game is 'stored', and didn't know it could disappear from 'recent'.

**Comment by leomcelroy** [comment]
Tried to clarify local storage by turning it into saving instead of recent. Can't have persistent urls with a backend which we don't want to add at the moment because the investment it incurs.
