### ISSUE TITLE
Suggestion: remove "What is the type of issue you're facing?" 

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#1452]
may be too hard for beginners, if they are "stuck" they probably don't what is
![image](https://github.com/hackclub/sprig/assets/88567622/ca78b922-0f00-4cf3-a68d-ec137481db06)

**Comment by JosiasAurel** [comment]
we want users to describe what they think the issue they're facing is. if they're not too sure they could also just ignore the field altogether

**Comment by LucasHT22** [comment]
> we want users to describe what they think the issue they're facing is. if they're not too sure they could also just ignore the field altogether

Alright, if that's your opinion who am I to disagree haha

**Comment by JosiasAurel** [comment]
@LucasHT22 you have the right to disagree and suggest a change. After all you have been doing a great job at reviewing most of the Sprig game PRs. Please forgive me if that came off as rude.

**Comment by grymmy** [comment]
I think a review of the specific fields choosable should be done to ensure we cover what we should.  Perhaps an "I don't know" option should be available.  Perhaps that should even be the default choice.
