### ISSUE TITLE
Confusing headers in new game files

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#1454]
This default header is inscrutable and intimidating to beginners. Users should be asked to add metadata when they submit their files to the gallery. Default files should not include information that can't be understood or filled in by users at the time of introduction.

Please remove the metadata tags from the default program.

<img width="733" alt="Screenshot 2024-02-23 at 4 29 40 PM" src="https://github.com/hackclub/sprig/assets/27078897/26834439-f2cf-4658-99e8-d261ecab0052">

**Comment by JosiasAurel** [comment]
I agree this might be intimidating for beginners. We could add a step to the submit instructions or leave it to Lucas who is already filling this metadata on PRs @grymmy ?

**Comment by grymmy** [comment]
Closing this as other issues track the details re: where we are going here.
