### ISSUE TITLE
Bug: False positive in some cases when trying to detect if something is touching something

### ISSUE THREAD

**Issue by quackduck** [hackclub/sprig#150]
Small demo ced made yesterday: https://sprig.hackclub.dev/?id=c58a2b84fd62f520e993dba0c096eb87
The trellis changes to a vine when the bean is touching. Notice the false positive when the bean is in the left-bottom corner.

**Comment by quackduck** [comment]
fix wen

**Comment by leomcelroy** [comment]
Fixed now!
