### ISSUE TITLE
Find sprig welcome note and add to sprig inventory sheet

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1509]
There is a "welcome to sprig" note that is supposed to come with each sprig and also link to the assembly instructions.

We need to:
1. Find (or recreate) this copy.
2. Add it to the Sprig Parts Inventory clipboard sheet w/ QR code (including link to doc / qr code).  Minimum # of items: 100
3. Add a line item in the Sprig Kit Assembly Guide for welcome note to be added to kit.
4. Print out 200 and put them in the sprig inventory area

**Comment by Sheepy3** [comment]
just need to print volume of them now.

**Comment by Sheepy3** [comment]
its been done
