### ISSUE TITLE
Add build instruction link to sprig-hardware

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1511]
Add build instruction link to sprig-hardware repo (both in original repo and in new sprig location).  This is the only URL given to sprigsters for old packaged sprigs - not having a convenient link to the assembly instructions here adds confusion.

**Comment by Sheepy3** [comment]
did it w/ https://github.com/hackclub/sprig-hardware/commit/e47d2e0f5940035edbfab065882032190967349a
