### ISSUE TITLE
preview levels on hover

### ISSUE THREAD

**Issue by cedric-h** [hackclub/sprig#152]

**Comment by cedric-h** [comment]
closed by 04a9a6ab69fabd7a605db17fa60ecf46ee93cabe

**Comment by cedric-h** [comment]
wrong issue

**Comment by leomcelroy** [comment]
This involves evaluating parts of the script like setLegend. Makes the preview quite a bite more involved than bitmaps. Let's punt for now, may or may not return to it later.
