### ISSUE TITLE
Sprig AI: Implement UI features to support the AI implementation

### ISSUE THREAD

**Issue by faisalsayed10** [hackclub/sprig#1528]
As per the discussion, this is the UI/UX flow we will be implementing for Sprig AI: https://docs.google.com/document/d/1GEAomQEqY00lmk_QoGSQsCnNzxO9tTbgljC7UvfNm8I/edit

<img width="1239" alt="image" src="https://github.com/hackclub/sprig/assets/36627266/bcb359be-6fb6-48f0-9f37-498beda74807">

A. User clicks on `Get solution`. Another modal pops up. The entire background is disabled. They either have to accept changes or reject them before they continue.

B. User clicks on `Get therapy`. A sidebar opens. The sidebar is collapsible. It doesn’t block the main UI. The user can simultaneously chat and code.

[See UI specifications, and rough mock-ups in the document shared above]

**Comment by faisalsayed10** [comment]
@leomcelroy please share thoughts

**Comment by leomcelroy** [comment]
Why are you leaning towards removing the user from the context of the editor (by popping up a full screen modal)?

**Comment by leomcelroy** [comment]
This feature would likely be used interactively and will necessitate editing code/re-running the game frequently. It seems it would be reasonably placed in the help panel (which currently is sized unreasonably small #829).

**Comment by leomcelroy** [comment]
It seems the first step in this project is demonstrating a performant result from an LLM. Do you have any examples of what sorts of questions one would ask and what answers you would receive.

**Comment by faisalsayed10** [comment]
Re: the results. If I recall correctly, we have a document with results and prompts for error cases that teens are facing while they're submitting the reports.

cc: @JosiasAurel

**Comment by JosiasAurel** [comment]
fwiw this does not contain the actual code/responses as they would be too long 

[Navigating prompts to help Sprig users resolve issues in their games..pdf](https://github.com/hackclub/sprig/files/14744946/Navigating.prompts.to.help.Sprig.users.resolve.issues.in.their.games.pdf)

**Comment by grymmy** [comment]
> It seems the first step in this project is demonstrating a performant result from an LLM. Do you have any examples of what sorts of questions one would ask and what answers you would receive.

We already have preliminary results/expectations set re: quality after doing manual testing using multiple LLMs.  We are currently working on getting hard #'s based on "I'm Stuck" data re: quality.

@leomcelroy I would request that we keep discussion at this point limited to the desired UX / UI - approval or disapproval of the "what" and not the "how".

**Comment by leomcelroy** [comment]
Place the chat in the panel where the help section is. Make sure that panel is resizable as described in #1363.

**Comment by faisalsayed10** [comment]
sounds good; starting implementation for both
