### ISSUE TITLE
Hardware KiCAD file is missing a library

### ISSUE THREAD

**Issue by ajs256** [hackclub/sprig#1532]
**Describe the bug**
When I try to open the hardware KiCAD file, it seems like there's a missing file.

**To Reproduce**
1. Download the KiCAD files
2. Open them
3. Try to open the footprint assignment tool in the schematic
4. See that some footprints (in a `fab:` library) are missing

<img width="1581" alt="image" src="https://github.com/hackclub/sprig/assets/67526318/259b9f03-50c8-4a28-885a-f6a06ffab03a">

**Comment by ajs256** [comment]
@leomcelroy do you have any idea about this? it's blocking a project I'd really like to work on

**Comment by leomcelroy** [comment]
I believe this is the library

https://gitlab.fabcloud.org/pub/libraries/electronics/kicad

They are not saved in the KiCAD file but layout information is.

**Comment by ajs256** [comment]
Thanks Leo, I'll check if that works soon. I'll PR a note in somewhere relevant if that turns out to be right.
