### ISSUE TITLE
Create new Theme picker dropdown in sprig editor

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1556]
![uxprop](https://github.com/hackclub/sprig/assets/109123711/7a7c04dc-7c26-405f-92ca-c6410db27562)
I propose adding a new dropdown to the UI which hosts the current two themes (default / darkmode) as well as a new "busker" theme in collaboration with "Penny's big breakaway"

**Comment by Sheepy3** [comment]
1. see revision below
2. dropdown should be visible in the editor, gallery, and "your games", beside the github link. 
3. theme changes should be reflected on the editor, gallery, and "your games". 
4. could potentially replace sprig dino with either penny's face or the logotext of the game
![image](https://github.com/hackclub/sprig/assets/109123711/44a0ece1-def8-4b9b-be23-740b59036713)
![image](https://github.com/hackclub/sprig/assets/109123711/5432bf39-edc8-445e-a62a-c744977a5344)
![image](https://github.com/hackclub/sprig/assets/109123711/838b4971-d8eb-4a45-a3ca-a5ff62a851b2)

**Comment by grymmy** [comment]
this looks great to me

**Comment by grymmy** [comment]
I'd vote for penny's face

**Comment by leomcelroy** [comment]
This theme picker sounds fine but we're crowding the top bar.

Please but this in the dropdown menu.

We should relocate some of the other buttons too ("I'm stuck", "Run on Device"). When running workshops I often see multiple people try to run games on the computer hitting run on device and be confused why the games don't work.

**Comment by grymmy** [comment]
I recommend we do any relocation of other existing features as separate work items.  @Sheepy3 can u log separate feature request issues for relocating those?
