### ISSUE TITLE
stylize gallery 

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1569]
![image](https://github.com/hackclub/sprig/assets/109123711/4f52d52d-2c27-434c-8977-2b73c5aca311)
The gallery UI is fairly simple and pleasing on it's own, but it could be nice to have it stylized more to look like a set of game cartridges. If we allowed the games to have their own artwork for the cartridge outside of a screenshot (as retro game cartridges often would), it would give game makers more freedom in how they present their game. we could preserve the usefulness of seeing in-game spritework by having the art switch to a gameplay screenshot or gif on hover. 

i drafted a design for what a sprig game cartridge might look like a while ago, seen here: 

![image](https://github.com/hackclub/sprig/assets/109123711/17f642d3-7281-4b41-b414-7a23dda8681c)

**Comment by grymmy** [comment]
@leomcelroy plz explicitly approve/deny this feature.

**Comment by leomcelroy** [comment]
I'll close as not planned.
