### ISSUE TITLE
Spade multi-game support

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#1601]
Support loading multiple games to Sprig. We'd use the last half of Sprig's flash (the first half is used for the UF2), breaking it up into 8 100kb slots.
This would break games that are <100kb, but there's potential for having the ability to have a game span multiple slots.

Users would be able to select one of ~8 games in a list from the Sprig console's boot screen. When uploading a game, the Sprig web client would specify the name of the game. Games can be deleted by the user using the Sprig console.

Functionality in Spade to change and delete slots will be wrapped in an interface to support future use of the SD card to store games and assets.

**Comment by recursiveforte** [comment]
@leomcelroy could I have your thoughts?

**Comment by leomcelroy** [comment]
I'm fine with this feature but would not consider it high priority. I think you should always be able to upload from the browser. It sounds like that would neccesitate adding the ability to delete a slot from the console. Also what happens if you have a large game. Is the mqx game size now limited?
