### ISSUE TITLE
Builds are not deterministic

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#1608]
**Describe the bug**
Compile date is compiled into the uf2, making builds not deterministic — they depend on the date. 

**To Reproduce**
`xxd spade.uf2 | grep 2024.len`
You should see: 
`0009a4c0: 3233 2032 3032 3400 6c65 6e20 3d3d 2031  23 2024.len == 1`

**Expected behavior**
Compile date is not included in the resulting binary.

**Comment by grymmy** [comment]
@recursiveforte is it clear to you exactly what needs to change to allow for byte-perfect replicable builds?

**Comment by recursiveforte** [comment]
fixed by #1614
