### ISSUE TITLE
Create a short video tutorials

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#1629]
We need to produce more support material for introducing people to Sprig.

Find one of your favorite games in the gallery.

Create a video tutorial where you first introduce the game and play it for about 5-10 secs.

Then quickly walk through  creating the game in 60 - 90 seconds.

For an example of this style of video check out [Coding Train's shorts](https://www.youtube.com/shorts/j6txbhwP9jo).

Make sure you have high quality audio and screen recordings (you can use OBS).

We would like as many of these as possible. Comment on this issue with the game you are going to be covering. Make sure to credit the original author if it is not you.

**Comment by grymmy** [comment]
@leomcelroy please create one issue per video that you want to **ensure** we create, each of which could be owned by an individual - we shouldn't dogpile on issues via commenting as you suggest here, we don't want eternal/everlasting/non-terminating issues w/ unclear ownership.

**Comment by grymmy** [comment]
@leomcelroy upon deeper thought I think we should just make this into a proper YSWS subproject under Sprig and provide awards to those that submit videos.  Whaddya think

**Comment by leomcelroy** [comment]
Great idea Graham! Kara, Shawn and I discussed something similar for the Sprig winter cases. Any ideas for what we should ship as rewards?

I still think the first step is to make some high quality videos ourself so people know what to aim for.

**Comment by grymmy** [comment]
@leomcelroy Will find an owner for this ticket today and will work on the plan for crowdsourcing content.

**Comment by grymmy** [comment]
@leomcelroy I will produce some video content this week and will collab with https://github.com/Deetschoe re: editing
