### ISSUE TITLE
Sprite Editor Issues

### ISSUE THREAD

**Issue by rithulkamesh** [hackclub/sprig#163]
1. I would definitely like more color choices in the palette
2. The lack of an eraser, and the use of a transparent brush made me kind of pissed
3. My sprite ended up getting messed up, no matter how many times I tried to fix it
![image](https://user-images.githubusercontent.com/45348760/180500415-b4f4beaf-4abb-4bf4-a71f-983599916134.png)

**Comment by leomcelroy** [comment]
Can you take a screen recording of editing the sprite and it getting jumbled?

I'm not sure what would be causing that.

We are going to adjust the color palette but it will still be small. Probably 16.

Having the "blank" color lets you erase with other drawing tools like the rectangle. If there was only an eraser it'd be like only having the brush for erasing.

**Comment by leomcelroy** [comment]
Were you using Brave?
