### ISSUE TITLE
Add instrumentation / logging to LLM backend

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1633]
Please ensure that we have robust logging, encompassing the full payloads sent to/from the llm service (this logging should be LLM provider-agnostic).  At minimum, we need to be able to inform ppl of how many AI-assisted interactions we enabled.  At maximum, it'd be good to save all requests and responses somewhere for future analysis and iteration/improvements.

**Comment by JosiasAurel** [comment]
implemented since https://github.com/JosiasAurel/llm-api/pull/6
