### ISSUE TITLE
Reskin "I'm Stuck" feature to be a bug reporting mechanism

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1639]
I believe it is useful to repurpose the "I'm Stuck" functionality to be a bug reporting mechanism - this would require *very* little change.  Basically:

1. Change "I'm Stuck" copy to "Report a bug"
2. Change dropdown to contain a more suitable enumeration of different bugs - for instance, ui / syntax / compilation / bitmap editor / tune editor / game window / login / chat

**Comment by grymmy** [comment]
@leomcelroy plz approve - I think this is somewhat important because we don't want to confuse people with two sources of "I'm Stuck" functionality once we launch the LLM chat feature.  This is a superior bug reporting mechanism than just linking to the GH issue template because it also uploads the entirety of the state of the editor, which helps in debugging.

**Comment by leomcelroy** [comment]
I approve doing this. Can I get a mock up of the UI? It could also be a modal that pops up and walks through reporting the bug.

**Comment by grymmy** [comment]
> I approve doing this. Can I get a mock up of the UI? It could also be a modal that pops up and walks through reporting the bug.

@leomcelroy there would be zero difference except for the button/UI copy and dropdown item contents (which I think we can iterate on - will put some reasonable placeholders for now).

**Comment by grymmy** [comment]
Fixed in #1649 and tested in prod
