### ISSUE TITLE
in errors: have line numbers which are highlighted

### ISSUE THREAD

**Issue by snoglobe** [hackclub/sprig#1651]
add code blocks to sprig errors, which are syntax-highlighted and have line numbers.
![image](https://github.com/hackclub/sprig/assets/25540164/d1e5dc5e-67bb-4431-9f94-52f15037136f)

**Comment by grymmy** [comment]
Two things:
1. The example given does show the proper information in the Sprig editor (i.e. Sprig does not show an inaccurate error in this situation)
2. This issue should be broken down into pieces.
* Extract exception name and error and display them separately, not in one text block
* Parse out the line and column information and make the error message align with the specific line of code and the column position where the error occurs
* Jump to line feature

**Comment by snoglobe** [comment]
broken into #1830, #1831, #1832
