### ISSUE TITLE
Preview branches are broken by default (you cannot successfully login)

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1656]
Due to the whitelisting that is done in Sprig, preview branches are broken by default.  A preview URL such as https://sprig-u0ol139ul-gamer.vercel.app/ does not allow one to login.

**Comment by JosiasAurel** [comment]
I've noticed preview URLs with `*-gamer.vercel.app` are the ones where login fails. After some digging I found there's another team called `Gamer` that automatically deploys the game submissions PRs

**Comment by JosiasAurel** [comment]
related #1145

**Comment by JosiasAurel** [comment]
Have setup a firebase project for preview deployments and removed the Gamer team (which does not belong to Hack Club) as a deployment environment from the Sprig project. I've tested and the preview deployment works fine and it's possible to log in.
