### ISSUE TITLE
description in sokoban puzzle is a bit misleading

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#167]
It says "walkthrough of this game is in help". there's no walkthrough of the game. :)

Current text: 
@title: sokoban
@author: leo

Instructions:

Cover the green with purple.

----------------------------

Welcome to Sprig!
Here is an example game to acquaint you with your toolkit.

You can find a walkthrough of this game if you hit help.

SUGGESTED TEXT:
@title: sokoban
@author: leo
Welcome! This code is good for people new to the Sprig engine!
for questions, see our HELP documention, or find us on Hack Club Slack in #sprig channel
TO PLAY:
Cover the green with purple.
Controls: WASD
----------------------------

**Comment by leomcelroy** [comment]
Issue is duplicate.
