### ISSUE TITLE
AI Help fails silently when the user isn't signed in

### ISSUE THREAD

**Issue by cjdenio** [hackclub/sprig#1725]
**Describe the bug**
The AI Help feature fails to give answers if you aren't signed in to a Sprig account.

**To Reproduce**
1. Go to https://sprig.hackclub.com/editor in an incognito session
2. Click on the "Get AI Help" panel
3. Ask a question
4. Observe
<img width="749" alt="Screenshot 2024-05-30 at 10 28 52 AM" src="https://github.com/hackclub/sprig/assets/34525547/534eab94-943f-4309-8507-9c0c9d7e4fdd">

**Expected behavior**

Maybe the panel could be greyed out when there isn't a user signed in?

**Screenshots**
<img width="418" alt="Screenshot 2024-05-30 at 10 29 12 AM" src="https://github.com/hackclub/sprig/assets/34525547/26682d0d-8ee6-49bd-9b7d-e1015e54a387">

**Comment by grymmy** [comment]
Thank you for this....  it shouldn't be available at all if you're not logged in!
