### ISSUE TITLE
"New PR" button in Editor view for games

### ISSUE THREAD

**Issue by snoglobe** [hackclub/sprig#1743]
re: [this thread](https://hackclub.slack.com/archives/C02UN35M7LG/p1717763257182089) 

add a button to bring game makers from editor page straight to GH new PR page, to reduce confusion.

**Comment by grymmy** [comment]
I am a super big fan of this feature.  Make it so plz

**Comment by snoglobe** [comment]
found that there is no easy way to provide a GH link that will do the required steps - so now just linking to the guide with a "Submit Game" button
