### ISSUE TITLE
Modal for naming game upon creation

### ISSUE THREAD

**Issue by snoglobe** [hackclub/sprig#1744]
Have a modal that forces the user to name their game (obviously keeping ability to rename it in the future) at creation, instead of auto-generating a name. When having multiple games it's easier to pick out one that you named than an auto-generated one, and having this modal would help with that. Just a nicety

**Comment by mrdarip** [comment]
I'm volunteering to work on this issue.

**Comment by mrdarip** [comment]
I'm volunteering to work on this issue.

**Comment by mrdarip** [comment]
I'm volunteering to work on this issue.

**Comment by DevIos01** [comment]
This has already been worked on and merged on #1944 as is live at sprig.hackclub.com so I am closing this!
