### ISSUE TITLE
Home screen UI is broken for some standard screen sizes

### ISSUE THREAD

**Issue by Cosmin-Mare** [hackclub/sprig#1859]
![image](https://github.com/hackclub/sprig/assets/147330889/ed42936f-a0ea-45b5-83f5-d898de44dd5a)

**Comment by snoglobe** [comment]
for ref. can you list the screen sizes this happens on? find the viewport size in your browser of choice pls

**Comment by claynicholson** [comment]
This should be fixed now for all screen sizes

**Comment by Cosmin-Mare** [comment]
![image](https://github.com/hackclub/sprig/assets/147330889/a96ba597-553e-4fb7-a3b7-b9923c078cd0)
it doesn't seem fixed @claynicholson

**Comment by Cosmin-Mare** [comment]
the size it's not working on is 1280x720

**Comment by claynicholson** [comment]
My pr hasn’t been accepted yet
