### ISSUE TITLE
Game shows up as "Unsaved game" and you cannot change the name of the game

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#1935]
This appears to be an issue just in the new saving strat (multi-user stuff).  
![Screenshot 2024-07-10 at 10 11 15 AM](https://github.com/hackclub/sprig/assets/43505167/0b7b92a5-aba4-490b-a1e5-ddc83c95c485)

**Comment by Cosmin-Mare** [comment]
the name change by attendees doesn't really make sense, but it should say the actual save state
