### ISSUE TITLE
create dropdown for ui options

### ISSUE THREAD

**Issue by ShubhamPatilsd** [hackclub/sprig#1953]
![image](https://github.com/user-attachments/assets/2ba2ac1e-66e0-4c39-8f68-8cf5aa14235d)

all the navbar items should be in a "..." button to the right of the run button

**Comment by grymmy** [comment]
Closing this in preference to https://github.com/hackclub/sprig/issues/1971 and https://github.com/hackclub/sprig/issues/1972
