### ISSUE TITLE
Make "Get a Sprig" UX more consistent w/ rest of app

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#2002]
Currently the "Get A Sprig" page uses the same green background and different style as the main landing page.  We want to move away from the different style for all pages *except* the main page.  So a few things need to happen here:

1. Make the top nav bar exactly the same as in the gallery.
2. Do away with the green background image.  Change color scheme of whole page to be more cohesive/aligned w/ rest of app.
3. Wrap the top copy (Share your game, etc, the whole paragrph there) in some eye-catching nice UI element.

**Comment by EerierGosling** [comment]
fixed in #2068
