### ISSUE TITLE
Online emulator doesnt get input with caps lock activated

### ISSUE THREAD

**Issue by mrdarip** [hackclub/sprig#2048]
**Describe the bug**
if you tray to play with caps lock activated it just doesnt dettect the keypress

**To Reproduce**
go to any game and activate caps lock

**Expected behavior**
to detect input

**Actual behavior**  
doesnt detect input

I guess its because onInput('s') and not onInput('S') but when discovered the "bug" i went crazy abou why wasnt my game working for no reason

**Comment by BrightTheBackpack** [comment]
Related to #1406 
What browser are you on?

**Comment by mrdarip** [comment]
chrome
Versión 127.0.6533.74 (Build oficial) (64 bits)

**Comment by youknowedo** [comment]
Can reproduce on Edge
Version 127.0.2651.98 (64-bit).
Dove into the codebase and I have little idea of what's going on. However, I'm pretty sure that the input already goes through a `toLowerCase()` before being passed on to Sprig. I also saw that we're using ThreeJs for the inputs, maybe they're the problem idk.
