### ISSUE TITLE
Sprig bootloop after flashing new firmware

### ISSUE THREAD

**Issue by cott3** [hackclub/sprig#2275]
**Describe the bug**

The Sprig keeps bootlooping (turning off and on, computer repeats connected and disconnected sounds) after I flashed the latest pico OS.

**To Reproduce**

Flash the latest OS (drag and drop to Pico in BOOTSEL mode)

**Expected behavior**

The Sprig boots successfully.

**Actual behavior**  

Bootloops.

**Screenshots** (skip to 0:50 and unmute audio)

https://github.com/user-attachments/assets/d9ecb3fd-cdcd-497b-aa31-ebdd303aade9

**Comment by recursiveforte** [comment]
Hey! Thanks for making this issue. Could you also upload a video of the Sprig device when it's bootlooping so I could get more info?
Also- have you used this Sprig/uploaded games to it before? Have you uploaded custom firmware, like the Doom port?

**Comment by cott3** [comment]
i cant but the screen flashes white
it worked after flashing the nuke uf2
yes, i had games before and had custom firmware (not the doom port tho)
