### ISSUE TITLE
instrument sprig collab feature

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/sprig#2303]
Add instrumentation to the sprig collab feature to collect telemetry. 
- Number of active rooms
- Number of active users 
- Overview of signaling server activity 
- miscellaneous

**Comment by Cosmin-Mare** [comment]
@JosiasAurel are you still working on this? I'm okay with taking ownership of this issue

**Comment by Cosmin-Mare** [comment]
I implemented instrumentation for: connection count, publishing count(edits), number of active rooms, is there anything more? If not, you can close this @JosiasAurel
