### ISSUE TITLE
High prio: Share your game page needs explicit instructions on how to 'win' a sprig

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#247]
Suggestion: 
GET A SPRIG CONSOLE!

Sprig consoles will be ready for shipping end of Sept 2022*. You can get on the waitlist now by sharing your game and having it approved by one of our project maintainers. Once approved, we'll collect your details for shipping.

If you have any questions, join #sprig on our Slack 

There are only a few requirements to get a Sprig console:
1. you must be in high school or younger (this will be checked before mailing)
2. your game must use the Sprig editor
3. your game must be winnable
4. your game has a minimum of 5mins of gameplay
5. your game is original

We'd love to play your game even if you aren't submitting for a Sprig console! Follow the steps below. 

* subject to availability for shipping

**Comment by karamassie** [comment]
love it. if we had hours and hours, i'd ask for the dino sprig logo but it's fantastic as is. TYYYY

**Comment by sampoder** [comment]
https://github.com/hackclub/sprig-gallery/pull/14 <- done!

**Comment by leomcelroy** [comment]
This issue seems to be a dupe (or closely related to) #261.
