### ISSUE TITLE
Tune editor freezes when modifying a tune speed in quick succession

### ISSUE THREAD

**Issue by Cosmin-Mare** [hackclub/sprig#2505]
**Describe the bug**
When you have a tune editor and modify the speed via the slider about 5 times rapidly, the editor freezes

**To Reproduce**
1. Open a tune editor(tune``)
2. Create some notes
3. Drag the speed slider and release it rapidly a couple of times

**Expected behavior**
Speed should change normally

**Actual behavior**  
Editor freezes

**Comment by JosiasAurel** [comment]
I'm unable to reliably reproduce this issue on my end
