### ISSUE TITLE
attempting to wipe a block of code freezes the editor 

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/sprig#2509]
Trying to wipe a block of code in the sprig editor freezes it. 

## Steps to reproduce
1. Create a new game project in the sprig editor
2. Select a block of code
3. Press delete
4. Notice that the block of code doesn't get deleted and the code editor is now unresponsive

## Expected behaviour
The block of code gets deleted

**Comment by polypixeldev** [comment]
Also getting this issue. Debugger in Firefox suggests an infinite loop happening at https://github.com/polypixeldev/sprig/blob/76e993c475424b5aa00d88ab4cb8fcedf9a192d3/src/lib/codemirror/util.ts#L66 (although not 100% sure)

**Comment by Cosmin-Mare** [comment]
I can't replicate this. for me it works as expected. I tried writing multiple functions and deleting multiple blocks of code but for me it doesn't crash or anything

**Comment by Cosmin-Mare** [comment]
could replicate, although it's sometimes inconsistent

**Comment by Cosmin-Mare** [comment]
it does freeze in the loop mentioned by @polypixeldev, and it freezes because the range is null and the line doesn't change between itterations, so the pos remains the same.

**Comment by Cosmin-Mare** [comment]
This is apparently fixed by breaking if the range is null. making a PR rn
