### ISSUE TITLE
med-hi prio : sprig logo top right needs new asset

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#258]
swap out sprig logo top right w/correct version pls
![sprig_youbastbard-01](https://user-images.githubusercontent.com/99233707/186924104-c228cfe8-e20a-4e41-823c-81df392e4b03.svg)
(for dark bgs)

![spriglogotext](https://user-images.githubusercontent.com/99233707/186924284-a495212a-b8b2-4017-9c33-fc6697608483.svg)
(for light backgrounds)

a little drop shadow on it can look nice

**Comment by leomcelroy** [comment]
can we add this to the editor so the same logo is on all pages

**Comment by sampoder** [comment]
Done on gallery! Where do you want it on the editor?

**Comment by leomcelroy** [comment]
where the github logo is probably. I like having the github link but the pages should be consist

**Comment by leomcelroy** [comment]
What was different about this logo asset? Lexi and I prefer the one with the enig gold flourish. Though it should match the color we use for that accent throughout the pages.

**Comment by karamassie** [comment]
my stroke is too thin (my fault), the official "sprig" has no dot over the i. I just sent lexi the goldie one

**Comment by leomcelroy** [comment]
Great! Think we got it then.
