### ISSUE TITLE
High prio:  text changes on the gallery page 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#259]
CURRENT :
The best way to learn is by making things that you care about and sharing them with other people.

Check out games by other Hack Clubbers! Click to play each game and to hack on the code.

Want to join in on the fun? If you have a Sprig game to share with the community, click here!

SUGGESTED: 
Check back frequently as more fellow Hack Clubbers add their games! 
Click to play each game and to hack on the code.

Ready to share your game to the gallery and begin your journey to getting a Sprig console:

**Comment by leomcelroy** [comment]
I prefer the current copy. 

I feel strongly about listing the learning philosophy explicitly. 

The gallery can be used even if you aren't obtaining a console. The instructions/copy in the gallery shouldn't suggest the only way to engage is through the hardware route. A vast majority of people using this won't get the hardware.
