### ISSUE TITLE
high prio: add plausible analytics to sprig pages

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#263]
request from @zachlatta

**Comment by sampoder** [comment]
https://github.com/hackclub/sprig-gallery/commit/e94ac1e03a2fd5dab3fc96f147a8bbbaa97d738a

**Comment by sampoder** [comment]
https://github.com/hackclub/sprig/commit/6456d1dbcf8f581ccb9c73845a4ff718565bc5d9
