### ISSUE TITLE
Add white noise "waveform" for a percussive sound

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#283]

**Comment by Yaswanth820** [comment]
Hey @leomcelroy , I am interested to work on this issue. Can you please give me some details and resources to get started?

**Comment by leomcelroy** [comment]
Great to hear you are interested! The idea is to add a sound that is more percussive to the current waveforms. White noise can be perceived this way. It'll need to be treated differently from other sounds as it won't have a pitch associated with it. One thing that may prevent us from ultimately integrating it into the editor fully is we also have to generate the sound on the Sprig devices itself.

Here is a resource to generating noise in JS: https://noisehack.com/generate-noise-web-audio-api/

**Comment by grymmy** [comment]
@leomcelroy I do not anticipate us working on this for the foreseeable future, especially as it's sat here for over a year.  I am closing it due to inactivity, if you feel strongly about reopening it, please do so w/ comment.
