### ISSUE TITLE
In submission guide add cue to write some prose with your pr

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#296]
Describe the game, maybe a bit about yourself

**Comment by LucasHT22** [comment]
my game is very simple, it's a balloon that goes through a maze. I did it with the intention of testing and understanding the sprig platform. The choice to be a balloon was due to being a "brand" of mine, whenever I'm learning a new language or tool I do something with balloons

**Comment by leomcelroy** [comment]
Added a line about this.
