### ISSUE TITLE
Visual bug when writing a "tune" line

### ISSUE THREAD

**Issue by maxwofford** [hackclub/sprig#303]
<img width="262" alt="Screen Shot 2022-09-07 at 13 17 09" src="https://user-images.githubusercontent.com/5891442/188941257-dd948243-a773-4f43-82c8-f35111ab642a.png">

some visual thing that was tripping me up– i’m actually editing the end of the line here, but the cursor shows up offset by 1.5 character widths. i can click the back of the line and it shows up correctly, but further typing seems to move me back to the offset (incorrect) position

showing on FF latest on mac

**Comment by SamDev-7** [comment]
This also seems to affect bitmaps and maps.

**Comment by kognise** [comment]
d538c3d :)
