### ISSUE TITLE
Expand Color Palette

### ISSUE THREAD

**Issue by Omay238** [hackclub/sprig#323]
This may not be possible with sprig hardware, but adding different shades of already integrated colors would be very useful for things such as shading and details.

**Comment by leomcelroy** [comment]
I've been looking at other color palettes actually. Unfortunately changing them would adjust how people's games look but we could try to match the general colors of the current palette with a more carefully designed one. 

Here are a few I was studying for inspiration:

https://androidarts.com/palette/16pal.htm

https://www.getty.edu/research/exhibitions_events/exhibitions/bauhaus/new_artist/form_color/color/

https://yeun.github.io/open-color/#gray

https://pico-8.fandom.com/wiki/Palette

**Comment by leomcelroy** [comment]
What colors would you add?

**Comment by Omay238** [comment]
I'm not sure what colors I would add, but a question: are more than 16 colors possible?

**Comment by leomcelroy** [comment]
It's possible yes. We limit the colors as a design constraint but technically the limit is the number of characters.

**Comment by Omay238** [comment]
How many total colors would be possible?

**Comment by Omay238** [comment]
I made a pretty similar one that could preserve old art if the colors were put correctly 
[https://Sprig-Color-Scheme.leonardmac.repl.co](here).

**Comment by Omay238** [comment]
The colors in hex are:
```
#000000
#555555
#aaaaaa
#FFFFFF
#800000
#C00000
#FF0000
#008000
#00C000
#00FF00
#000080
#0000C0
#0000FF
#808000
#C0C000
#FFFF00
#008080
#00C0C0
#00FFFF
#800080
#C000C0
#FF00FF
```

**Comment by leomcelroy** [comment]
How did you choose these? Are they just evenly spaced?

**Comment by Omay238** [comment]
I got the half and three quarters brightness versions of all the original colors. I also changed the lighter gray to be a bit brighter.

**Comment by Omay238** [comment]
I do like the original. It's a nice amount of pure colors that can be used for simple art. My additions would probably just be used for shading.

**Comment by Omay238** [comment]
Do you think you could have up to 36, letters and numbers?
I'm trying to make a new palette that is more diverse.

**Comment by LucasHT22** [comment]
@Omay238 I suggest adding these colors:![Screenshot_20220914-190758~2.png](https://user-images.githubusercontent.com/88567622/190271835-efaf6aff-9db2-4005-8f78-42a7c4e31f4a.png)

**Comment by zachlatta** [comment]
Is there a technical constraint preventing us from supporting all colors?I know there is a vibrant community of people who love pixel art - especially middle schoolers, and I’d love for pixel art to be a “handle” for them to grasp to get deeper into their Sprig games. See https://www.pixilart.com/ for an example.For that to happen, I think we would need to be able to support arbitrary colors.On Sep 14, 2022, at 18:10, Lucas ***@***.***> wrote:﻿
@Omay238 I suggest adding these colors:

**Comment by Omay238** [comment]
I don't know how hard this would be, but a potential solution is have some sort of function (like setPalette()) to change the palette to some custom one. From what I understand, the colors used can be changed, using sprig hardware, but it would just be a matter of software.

**Comment by leomcelroy** [comment]
We can't do arbitrary colors because there needs to be a map to characters. That's good thinking Leonard there actually is a setPalette function which Ced and I discussed documenting. It should just work though I'm forgetting where we landed on exposing it. I do think the limited palette helps people with creativity (limitations effect in this way being a theme of the whole system).

**Comment by leomcelroy** [comment]
I've consistently settled on less than 16 colors being preferable. I'd like to take a closer look at the palettes you're (@Omay238) suggesting though. It's possible to have 36 yes though that many would involve changes to the interface I think.

**Comment by LucasHT22** [comment]
@leomcelroy I agree that the reduced palette helps people with creativity, but at least brown should be added, because without brown you can't make a tree

**Comment by Omay238** [comment]
I tested a new color palette, which just adds darker shades and browns, which you can see doesn't really make it easier to make art, but the abilities are just greatly expanded.
It also doesn't require extra code for making it look good. I think that was already changed with my issue about lots of sprites.
![colors](https://user-images.githubusercontent.com/70179858/191156085-2bbca84d-8003-4a5a-af9d-8e66865ef695.png)

**Comment by Omay238** [comment]
I can make a PR with the updated palette.

**Comment by LucasHT22** [comment]
@Omay238 , just a small formatting error, in the formatting
from the current color palette, has 6 colors per row, while yours has only 5
![Screenshot_20220920-064358.png](https://user-images.githubusercontent.com/88567622/191226099-eabb3804-5651-4ef0-b863-1a6e570fff3e.png)
![Screenshot_20220920-064213~3.png](https://user-images.githubusercontent.com/88567622/191226129-3a73f1bd-e770-409e-92e7-3dffadb0ced4.png)

**Comment by leomcelroy** [comment]
On the formatting, I think that's just the flex box.

@Omay238 could you trim it down to 16 colors? I like what you're doing but it feels it's getting away from the minimalism.

**Comment by Omay238** [comment]
I feel like this one allows more detail than the original, and it is 16 different colors. How do you feel about it?
![colors2](https://user-images.githubusercontent.com/70179858/191375305-d35c80ea-e81f-4f8b-be97-a5184dd41a85.png)

**Comment by LucasHT22** [comment]
Keep at least 1 shade of brown, without brown you can't make a tree or woods, it's a big barrier

**Comment by leomcelroy** [comment]
@Omay238 Thanks so much for pushing this issue! I've been really wanting to make the palette nicer and spent a couple hours looking at your suggested palettes and the feedback others gave this week. @kognise and I integrated that into the editor today and you can see the new palette on [this branch](https://sprig-git-new-colors.hackclub.dev/). 

<img width="344" alt="Screen Shot 2022-09-23 at 12 22 14 PM" src="https://user-images.githubusercontent.com/27078897/192007289-23e17bd9-eeaa-4c97-ac43-9dfd2623da88.png">

**Comment by LucasHT22** [comment]
Good color palette, doesn't lose Sprig simplicity

**Comment by Omay238** [comment]
I agree. It looks pretty good. Anyways, I'll close this issue now.
