### ISSUE TITLE
editor page logo isn't correct

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#330]

**Comment by exu3** [comment]
Which is the correct one? Is it this?

![image](https://user-images.githubusercontent.com/72365100/189354297-5e072216-c714-4474-8393-17db77e74e33.png)

**Comment by karamassie** [comment]
yes!

**Comment by leomcelroy** [comment]
We use the white outline on gallery and the editor. Lexi and I agreed the white one looks better on the sites it's on and always leads to the home page. The gold one is on the home page.

**Comment by karamassie** [comment]
ok.
