### ISSUE TITLE
wishlist: add a TOC after intro on toolkit

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#339]
for eg:
General hints/use
Variables
How to upload
Guide on what works/doesn't in engine

etc

**Comment by leomcelroy** [comment]
I also would like this. Unfortunately the rendering system makes it a bit cumbersome for the table navigation to work. So it's possible but might incur a maintenance cost. I took note of this feature: https://github.com/hackclub/sprig/blob/main/docs/BACKBURNER.md
