### ISSUE TITLE
wishlist: lighting on sprig device needs another pass

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#340]
it's VERY high contrast still.

**Comment by leomcelroy** [comment]
@maxwofford Did you take a pass at this?

**Comment by alhardwarehyde** [comment]
@leomcelroy @maxwofford Pinging this- is this something we're looking into?

**Comment by maxwofford** [comment]
I don't think this is active anymore. Can probably close as won't fix. I'm not 100% sure if this is referring to the contract on the device's screen or the editor's screen.

**Comment by alhardwarehyde** [comment]
Closing it for now thanks!
