### ISSUE TITLE
idea/wishlist: callout fun sound and sprite editor(s)

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#343]
we talked about doing this on Hype page

**Comment by leomcelroy** [comment]
For issues we aren't immediately going to address let's take note of them in [this doc](https://github.com/hackclub/sprig/blob/main/docs/BACKBURNER.md). I want to test out keeping the filed issues high priority/things we are currently working on. We can reopen these if/when we return to them in the future.
