### ISSUE TITLE
bug? mobile version 500 errors

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#344]
I've had it almost every time i first load page. Zrl has had it twice now too.

**Comment by sampoder** [comment]
theoretically resolved by https://github.com/hackclub/sprig-gallery/pull/21

**Comment by sampoder** [comment]
(am monitoring for future occurrences and keeping open for a couple of days)

**Comment by LucasHT22** [comment]
Hey, for me this error is momentary, whenever a new game is added to the sprig the site crashed, yesterday, when they were adding new games, the Hack Club sites were very unstable (I have a print screen). After Sam's change (https://github.com/hackclub/sprig-gallery/pull/21), I no longer had this problem
(hope I helped :), if I just get in the way, sorry)

**Comment by leomcelroy** [comment]
We love the participation @LucasHT22 and it's helpful to hear about your experience with the crashes. I also observed it seems to be related to when the site rebuilds.

**Comment by leomcelroy** [comment]
Lexi added some other safety features to the code so I'll close this now and we can reassess if it comes up again.
