### ISSUE TITLE
Mobile issue: demo game only goes right

### ISSUE THREAD

**Issue by maxwofford** [hackclub/sprig#348]
![IMG_8394](https://user-images.githubusercontent.com/5891442/189438561-87e4bca6-dcb0-4d18-971c-7a51318317ef.PNG)

When I click this game the "d" key moves me right, but the "a" key doesn't move me back to the left

**Comment by leomcelroy** [comment]
This is in fact the game, it's the tutorial. We discussed changing the default game for mobile for this reason.

**Comment by maxwofford** [comment]
Looks like I misunderstood the game inputs– "a" isn't bound to anything: https://github.com/hackclub/sprig/issues/349#issuecomment-1242531419. "j" is bound to left, which works correctly.
