### ISSUE TITLE
Mobile issue: selecting buttons

### ISSUE THREAD

**Issue by maxwofford** [hackclub/sprig#349]
![IMG_956ECD5396A6-1](https://user-images.githubusercontent.com/5891442/189438769-889b284a-1438-4a33-a13c-bc02f9f8706d.jpeg)

When I click and hold on mobile it tries to select the text of the buttons

**Comment by LucasHT22** [comment]
> ![IMG_956ECD5396A6-1](https://user-images.githubusercontent.com/5891442/189438769-889b284a-1438-4a33-a13c-bc02f9f8706d.jpeg)
> 
> When I click and hold on mobile it tries to select the text of the buttons

In Google Chrome he doesn't select, he just walks right with d and left with j, despite that, it's not possible to complete the game level
https://user-images.githubusercontent.com/88567622/189454619-83dd6a81-4f26-459c-bafc-01de7dd42ac6.mp4

**Comment by kognise** [comment]
CNR on Android Chrome or desktop emulating, and the buttons should have `user-select: none`. iOS Safari bug?

**Comment by kognise** [comment]
lol what's wrong with safari, it requires `-webkit` prefixed user-select. i hate safari.
