### ISSUE TITLE
Editor Folding in Ternary Operators

### ISSUE THREAD

**Issue by LinusSkucas** [hackclub/sprig#360]
<img width="634" alt="Safari + Sprig @ Saturday 09 10 2022 - 22 39 14" src="https://user-images.githubusercontent.com/19542092/189514181-af5e0cdb-d0df-4d33-bb0e-1597aba0cf10.png">
In a ternary operator only the first bitmap is folded, while the second one isn't. Ternary operators are nice for things like having a debug mode. I'd expect that both of the bitmaps could be folded and unfolded together.

**Comment by leomcelroy** [comment]
As far as we can tell CodeMirror doesn't support multiple folds on the same line. Given that we're going to close this as unplanned but I'll note it in our wishlist doc.

**Comment by kognise** [comment]
(You can always put the two sides of the ternary on different lines and the folding should work fine! I wish CodeMirror was better at this; I've had a similar annoyance working on my game
)
