### ISSUE TITLE
Storage Abstraction for Games

### ISSUE THREAD

**Issue by LinusSkucas** [hackclub/sprig#362]
It'd be nice to have an API that games could use to access storage, whether that be on a physical device, or local storage in a browser. Two potential use cases for an API like this:
1. A game can write a high score to a file so it can keep track of it.
2. A player could import new levels into a game through files.
Abstracting this would make it so that games don't need to add extra logic to determine if it should be saved by the browser or on an actual file system.

**Comment by UserJHansen** [comment]
I think this is possible in the js implementation on the Sprig as it is provided by kaluma, maybe a web interface is all that is required?

**Comment by UserJHansen** [comment]
#365 should enable this

**Comment by leomcelroy** [comment]
I took note of this in [this doc](https://github.com/hackclub/sprig/blob/main/docs/BACKBURNER.md) and will close this issue as not planned for now.
