### ISSUE TITLE
How to remove particular sprite from particular Position?

### ISSUE THREAD

**Issue by souvikpal2000** [hackclub/sprig#369]
If a tile contains more than one sprite, how I can remove a particular sprite from that tile without harming other sprite present in that tile?

In HELP SECTION of the editor, I haven't notice any kind of function that can perform above mentioned Functionality.

**Comment by leomcelroy** [comment]
Can you send the exact example you have in mind?

**Comment by Omay238** [comment]
A way that works is
```
function removeSprite(x, y, spriteType){
  var sprite = getTile(x, y);
  sprite[sprite.map(x => x.type).indexOf(spriteType)].remove();
}
```
Then just do
```
removeSprite(0, 0, player);
```
Then the sprite with type player at the top left corner will get removed.

**Comment by souvikpal2000** [comment]
> A way that works is
> 
> ```
> function removeSprite(x, y, spriteType){
>   var sprite = getTile(x, y);
>   sprite[sprite.map(x => x.type).indexOf(spriteType)].remove();
> }
> ```
> 
> Then just do
> 
> ```
> removeSprite(0, 0, player);
> ```
> 
> Then the sprite with type player at the top left corner will get removed.

Nice, this logic haven't came into my mind. Thank You
