### ISSUE TITLE
Suggestion: Open option for translation

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#374]
Like the Hack Club main page, I think the Sprig website could be translated into other languages.
I volunteer to translate to Portuguese :)

**Comment by RoloTheDevBunny** [comment]
How is the google translate version? I understand it's not perfect but for a small organization translating languages and getting trust worthy people to do it could be difficult.

**Comment by RoloTheDevBunny** [comment]
Yeah I just saw no one had replied to the post so I gave some ideas as to why I think they haven't done much localization. Hope they can translate at some point and make applications for volunteer translators.

**Comment by alhardwarehyde** [comment]
@LucasHT22 is there a specific feature ask here? How do we handle this on the main hack club website?

**Comment by LucasHT22** [comment]
For the Brazilian community it was solved with a dedicated repository, for me it can be closed

**Comment by alhardwarehyde** [comment]
Thanks Lucas! Closing this out!
