### ISSUE TITLE
'filename' in metadata.json is not used in the gallery

### ISSUE THREAD

**Issue by SamDev-7** [hackclub/sprig#398]
An example is [Line 142-148](https://github.com/hackclub/sprig/blob/98968717285903fcff4fb5f49b4cc87d12482677/games/metadata.json#L142-L148) where the `filename` is `reactor` but the `title` is `reaction_timer`. The file in this case is [`reactor.js`](https://github.com/hackclub/sprig/blob/main/games/reactor.js).

When visiting the gallery, the game links to https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/reaction_timer.js which will 404. 
It seems like it is using `title` field.

The url should use the `filename` field.

**Comment by leomcelroy** [comment]
Good eye! You've caught a sloppy half commit by me. I wanted to switch over to moving filename and added it to the metadata so I wouldn't have to update every game when I changed the gallery page loading function.
