### ISSUE TITLE
bug due to changes to issue #249?

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#399]
Header is fixed and filter options are white.

https://user-images.githubusercontent.com/88567622/191386519-9e8104ca-e6c9-4445-8ce9-7acdd83e7cda.mp4

**Comment by LucasHT22** [comment]
(Latest version Google Chrome)

**Comment by Omay238** [comment]
Alright. I fixed it in [this pr](https://github.com/hackclub/sprig-gallery/pull/24). Now I just have to get someone to approve it.
