### ISSUE TITLE
Google Chrome mobile version: Delete empty filter


### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#406]
![Screenshot_20220925-210429~2.png](https://user-images.githubusercontent.com/88567622/192171870-4a6d912e-9e3d-43e7-afd6-fde3694777cd.png)

**Comment by Omay238** [comment]
Yeah, that shows up on other versions. Not sure what the problem with that is.

**Comment by LucasHT22** [comment]
@Omay238 I think it's from having games without # , so the program understands that # empty is an option too

**Comment by Omay238** [comment]
Yeah, I agree. I think I might be able to fix it by changing metadata.json, but I'm not sure. I might be able to add tags to games without them.

**Comment by Omay238** [comment]
I fixed it in [this pr](https://github.com/hackclub/sprig-gallery/pull/25).

**Comment by LucasHT22** [comment]
I saw it now on the Sprig website and it's resolved, congrats @Omay238
