### ISSUE TITLE
Pixel editor sometimes mangles bitmaps in Arc

### ISSUE THREAD

**Issue by cjdenio** [hackclub/sprig#407]
https://user-images.githubusercontent.com/34525547/192430854-f278c49c-8fd1-4fc4-b477-e76d5b2dd3e5.mov

It looks like some of the pixel data from `ctx.getImageData` is slightly off.

I can't reproduce this in any other Chromium-based browser.

**Comment by kognise** [comment]
CNR in latest Arc, are you still having this issue?

**Comment by cjdenio** [comment]
Can't reproduce this on the computer I'm currently on— I'll make sure it's also fixed on my main machine

**Comment by kognise** [comment]
Truly horrible bug. Apparently canvas will occasionally slightly mangle colors, rendering a single channel off by one. When this happens and which channels are mangled seems to be up to entropy and this only happens on some browsers on some computers (and not a set with any seeming pattern, either). I'm just writing to an ImageData directly now and skipping the offscreen canvas, and all seems to be well :)
