### ISSUE TITLE
add pagination to gallery

### ISSUE THREAD

**Issue by Omay238** [hackclub/sprig#426]

**Comment by LucasHT22** [comment]
How would it be?

**Comment by Omay238** [comment]
Like having some amount of games on each page, choose a page at the bottom.

**Comment by leomcelroy** [comment]
I'm not sure I see a need for this now. Maybe if we have hundreds of more games it will become necessary. I think I still prefer infinite scrolling. Is a there a particular reason you suggest this?

**Comment by Omay238** [comment]
On some slower devices, it can take a while to load everything. For instance, a new computer I got is only 4gb of RAM, and it takes a while to load. Limiting it to say, 20 items on each page could make it faster.

**Comment by alhardwarehyde** [comment]
@leomcelroy given the feedback below do we want to do this?

**Comment by SamDev-7** [comment]
We could add a dropdown that allows the user to choose the amount of games to display per page, up to all at once.

**Comment by kognise** [comment]
I believe this isn't an issue anymore? The new gallery, in my experience, is a *lot* more performant than the old one. I'm gonna close this but if it's still an issue I guess we can look into pagination (or just more perf optimizations).
