### ISSUE TITLE
Audio editor crashes when changing the bpm of a song while playing it.

### ISSUE THREAD

**Issue by RoloTheDevBunny** [hackclub/sprig#430]
If you try to change the boom of a song while it is playing, the editor starts to spam the notes and they don't stop until you reload the tab. It would be nice if we could easily hear how different tempos could affect our audio. If this isn't possible, having the bpm box grayed out or having it not take effect until the song finishes and repeats would be nice.

**Comment by leomcelroy** [comment]
Could you post an example of this? We're having trouble recreating it. Screenshots, screen recordings, and code snippets would help.
