### ISSUE TITLE
Bug: Sprig Gallery doesn't correctly render game image



### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#439]
Same error observed in Breakout is appearing in all recent ones, no longer a one-off error

**Comment by LucasHT22** [comment]
![Screenshot_20221008-024343.png](https://user-images.githubusercontent.com/88567622/194691057-b466047b-6aa5-4e1e-a091-7518478c18ce.png)

**Comment by LucasHT22** [comment]
background isn't rendering

**Comment by Omay238** [comment]
Yeah, I noticed that problem as well. The only solution I can think of is just getting images for the games with backgrounds. There might be some way to include the `setBackground()` function in the card though.

**Comment by leomcelroy** [comment]
We can fix the thumbnail generation code.

**Comment by leomcelroy** [comment]
And we have. Thanks for the prompt.
