### ISSUE TITLE
addText renders non-alphanumerical characters incorrectly

### ISSUE THREAD

**Issue by SamDev-7** [hackclub/sprig#441]
![image](https://user-images.githubusercontent.com/66446458/194977517-a58c26d1-f826-4122-9a64-c2281231fb2a.png)
![image](https://user-images.githubusercontent.com/66446458/194977533-f2a9b5d0-bff8-4104-8339-900f30378262.png)
---
![image](https://user-images.githubusercontent.com/66446458/194977557-aae49193-f6a1-4eef-a39a-eb34dce538e3.png)
![image](https://user-images.githubusercontent.com/66446458/194977566-ae09dfbb-0aad-4fa8-ba65-daf84b454523.png)

**Comment by leomcelroy** [comment]
These symbols just aren't in the font. Which is fine I believe? Should we give some other sort of error?

**Comment by LucasHT22** [comment]
maybe an error "these characters aren't allowed"

**Comment by alhardwarehyde** [comment]
@grymmy can you try reproducing this?

**Comment by grymmy** [comment]
@leomcelroy is the proposed text okay with you?

**Comment by leomcelroy** [comment]
Proposed text is fine with me, good to implement.

**Comment by grymmy** [comment]
Yes the issue has all information.  It's very low priority though so I doubt I'll be getting to its actual implementation for a while - unassigning self.

**Comment by Omay238** [comment]
I think that I'll work on this. All I know is that the following characters are in the font:
!\"#%&\'()*+,./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\^_`abcdefghijklmnopqrstuvwxyz|~¦§¨©¬®¯°±´¶·¸ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ÙÚÛÜÝÞßàáâãäåæçèéêëìíîïñòóôõö÷ùúûüýþÿĀāĂăĄąĆćĊċČčĎĐđĒēĖėĘęĚěĞğĠġĦħĪīĮįİıŃńŇňŌōŒœŞşŨũŪūŮůŲųŴŵŶŷŸǍǎǏǐǑǒǓǔˆˇ˘˙˚˛˜˝ẀẁẂẃẄẅỲỳ†‡•…‰⁄™∂∅∏∑−√∞∫≈≠≤≥◊
