### ISSUE TITLE
bug: search bar not working

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#447]
![image](https://user-images.githubusercontent.com/88567622/195465322-21675c06-9e44-4e8d-92b7-42763659e1ee.png)

**Comment by Omay238** [comment]
What do you mean? Is it because there are no Sokoban games loading? If so, you have a typo. You wrote "skoban" with no "o" in the beginning.

**Comment by LucasHT22** [comment]
my bad, sorry
