### ISSUE TITLE
Sprite.remove()

### ISSUE THREAD

**Issue by Agent-Shu** [hackclub/sprig#461]
How can I remove a particular Sprite without removing other sprite if their pos(x,y) is same.
for eg: I have sprite named laser at pos 8,4

**Comment by LucasHT22** [comment]
this can help you
[https://github.com/hackclub/sprig/issues/369](https://github.com/hackclub/sprig/issues/369)

**Comment by Agent-Shu** [comment]
oh, I get it now. Thanks
