### ISSUE TITLE
Error messages are hard to understand

### ISSUE THREAD

**Issue by bellesea** [hackclub/sprig#468]
some error messages are hard to understand; some common ones when building your first sprig game (tested in coding club with 6th graders)

situation 1: not having a comma between elements in setLegend()
<img width="1044" alt="Screenshot 2022-10-19 at 5 27 20 PM" src="https://user-images.githubusercontent.com/65808924/196971932-0627df91-55d6-4585-b56a-40c9420273d7.png">

situation 2: forgetting closing brackets
![Uploading Screenshot 2022-10-19 at 5.29.04 PM.png…]()

situation 3: trying to access the position data of a sprite that is not on the map
<img width="1040" alt="Screenshot 2022-10-19 at 5 30 09 PM" src="https://user-images.githubusercontent.com/65808924/196972077-455fd2ae-329b-49e1-863b-70e0be92b935.png">

**Comment by alhardwarehyde** [comment]
@kognise I know we were talking about this issue before and how we're using the browsers or some other third parties debugging? So modifying error messages is hard- is that correct?

**Comment by kognise** [comment]
We probably won't do anything about either of these errors; that would require changing fundamentals of the JavaScript language which I'm against doing. I would argue the second example you gave is actually good. Another note is that new editor features stack traces which should be a lot easier to read and more like actual JS (and thus more Googleable as well).

While I'm not for adding errors for syntax things, I do think there are probably places in the codebase where internal Sprig errors could be added— for example, passing an empty object to `setMap` or something. Gonna make a separate issue #972 for doing an error reporting pass on the codebase.
