### ISSUE TITLE
bug: filter by tag has a white background

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#471]
![image](https://user-images.githubusercontent.com/88567622/197074364-ca3ba136-4312-4c65-879c-0686c1addfc1.png)

**Comment by Omay238** [comment]
Yeah, Kognise broke it in [this](https://github.com/hackclub/sprig-gallery/commit/94295f3053f62d92818e26c63c252a361b288e3d) commit. I'm gonna fix it in a PR soon.
