### ISSUE TITLE
Saves many different files when changing name

### ISSUE THREAD

**Issue by Omay238** [hackclub/sprig#476]
Make a game, and change the name. Then check your saved files.

**Comment by Omay238** [comment]
Here is a demo:
[Screen recording 2022-10-22 8.01.10 PM.webm](https://user-images.githubusercontent.com/70179858/197369584-8773d5c3-47d4-414e-a085-0eff69c4e76f.webm)

**Comment by LucasHT22** [comment]
![image](https://user-images.githubusercontent.com/88567622/197369667-94834582-d562-41a7-a5f3-2fafbd985ac5.png)

**Comment by Omay238** [comment]
Yeah, Kognise made it so that every key press saves again, so if you are changing the name, it will count as a keypress, and be a different file.

**Comment by kognise** [comment]
Ha, totally forgot this would be a thing. I can rollback my commit for now and actually fix this on Tuesday.

**Comment by LucasHT22** [comment]
I don't think reverting, because it's something you can fix manually by deleting the duplicate files and the auto-save function is very useful

**Comment by Omay238** [comment]
Yes, many times it has saved me from losing an hour of progress lol

**Comment by leomcelroy** [comment]
Thanks for pointing this out. What do we think the correct behavior should be?

**Comment by LucasHT22** [comment]
maybe if the filename change is independent of the changes in the file itself, wouldn't have this bug

**Comment by LucasHT22** [comment]
it's like a VS Code/Google Docs/Word, you change the filename separate from the text/code changes

**Comment by leomcelroy** [comment]
But we want to store files as just js so we need to encode the name in it somehow. That's why we have those special comments like `@title:`

**Comment by LucasHT22** [comment]
oh, ok
