### ISSUE TITLE
editor bigger than it should

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#479]
https://user-images.githubusercontent.com/88567622/198382616-a87a2d48-6363-4411-8994-79fb27bda837.mp4

I'm not sure but the solution might be add scrollbar in file, because it gets bigger so you can see all your files

**Comment by Omay238** [comment]
I'll try to work on that. Might fix it today, maybe tomorrow.

**Comment by leomcelroy** [comment]
Got it! Nice catch.
