### ISSUE TITLE
Can't select search box when gallery first loads.

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#487]
![Screen Recording 2022-11-02 at 12 13 51 PM](https://user-images.githubusercontent.com/27078897/199547172-9189280d-b6ba-43be-8d69-1dfeb7fda928.gif)

**Comment by kognise** [comment]
yeah. i know why this is happening. i can apply a jank solution.

(the event listener for the 3d sprig isn't being cleared on page transition)
