### ISSUE TITLE
security issue: cross site scripting in file load

### ISSUE THREAD

**Issue by the456gamer** [hackclub/sprig#496]
Demo: open url and click run

https://editor.sprig.hackclub.com/?file=https://gist.githubusercontent.com/the456gamer/c539813d9902185578d799f3aaed9772/raw/d152b2b85ccdaf4d3067a906c50c04e0c5ae76e8/my-cool-sprig-game.js

file source: https://gist.githubusercontent.com/the456gamer/c539813d9902185578d799f3aaed9772/raw/d152b2b85ccdaf4d3067a906c50c04e0c5ae76e8/my-cool-sprig-game.js

this abuses the fact that the JavaScript isn't sanitised before being run (another demo i had was using a fetch() to send/receive information)
and that arbitrary scripts can be loaded with the ?file= parameter

**Comment by alhardwarehyde** [comment]
@grymmy can you reproduce this?

**Comment by grymmy** [comment]
Will attempt to reproduce thus tomorrow.

**Comment by kognise** [comment]
This isn't relevant anymore.
