### ISSUE TITLE
feedback: people not seeing link to slack for help

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#501]
suggestion: move "If you ever need help, have ideas, or want to meet other game-makers, join the community in the [#sprig](https://hackclub.slack.com/archives/C02UN35M7LG) channel on the [Hack Club Slack](https://hackclub.com/slack)."

and put it in bold 

copy change suggestion:
Join  [#sprig] (https://hackclub.slack.com/archives/C02UN35M7LG) channel on the [Hack Club Slack](https://hackclub.com/slack) for help, or if you have ideas or just want to meet other game makers and sprig enthusiasts.

**Comment by sonicx180** [comment]
I think it's in the code editor when you click open help.

**Comment by alhardwarehyde** [comment]
@leomcelroy is this something we want to do?

**Comment by karamassie** [comment]
this has been improved since the feedback was logged, looks great now!
