### ISSUE TITLE
Differentiate between a short and long click?

### ISSUE THREAD

**Issue by Looky1173** [hackclub/sprig#510]
Is there a way to differentiate between a short and long click of a button? Could someone help me with doing this? Thank you!

**Comment by LucasHT22** [comment]
it's not possible... because on the keyboard there is no such difference

**Comment by Omay238** [comment]
Also, I don't think that it is planned for the actual console. I saw ced say that in some PR or Slack thread.

**Comment by LucasHT22** [comment]
it is not because there is no availability of parts and it would be more expensive, I saw Hugo talking about it
