### ISSUE TITLE
I am under 18, can i still recieve a free sprig?

### ISSUE THREAD

**Issue by SwiftyProgrammer690** [hackclub/sprig#535]
Is the deadline finished to receive a free sprig if you are under 18?
And if I am under 18, can I still receive a free sprig? Thank you!

**Comment by exu3** [comment]
If you make a game and add it to the gallery, you can still get a Sprig!

**Comment by SwiftyProgrammer690** [comment]
alright cool! i will amek sure to make a pr and submit my game to the gallery to receive my sprig! thanks @exu3

**Comment by SwiftyProgrammer690** [comment]
I just made a PR! #554
