### ISSUE TITLE
Having more than 4 sprites on a tile causes some to not show up.

### ISSUE THREAD

**Issue by Omay238** [hackclub/sprig#552]
Found in SOS_Game 
https://editor.sprig.hackclub.com/?id=222540d70cace129bca4b34be13a3482

**Comment by leomcelroy** [comment]
I believe there was a hard cap of sprites on each tile. While addressing this though I found some other minor bugs with the webgl rendering and ended up rewriting the renderer to use canvas. It's the simpler (less performant) way to do things but it seems to work well in the browser so I'm inclined to use it. 

Another advantage of the rewrite is that I removed the text canvas (only one game canvas now), which will allow the sprig engine to be used more easily as a library.

**Comment by leomcelroy** [comment]
Should be addressed now with new renderer.
