### ISSUE TITLE
"fix bugs yarn test" edit to my game kinda broke it

### ISSUE THREAD

**Issue by troy7615** [hackclub/sprig#555]
@LucasHT22 not attacking you or anything, but the edits you made to the player movement kinda messed up the ufo's movement, making it move two tiles instead of one. This makes the first level unbeatable.

**Comment by LucasHT22** [comment]
sorry, my bad! I will revert the changes and analyze

**Comment by troy7615** [comment]
It's all good, I can't count how many times I broke my own game while designing it

**Comment by LucasHT22** [comment]
is that when I run the yarn test command, it is returning this error to me:
![image](https://user-images.githubusercontent.com/88567622/201549903-269481e3-017e-4dde-8879-feef992fe478.png)

**Comment by LucasHT22** [comment]
switching between property x and y

**Comment by LucasHT22** [comment]
I thought this change would not affect the game, we already use it in other games

**Comment by troy7615** [comment]
I think the errors occur only on the end screen when it says you win

**Comment by LucasHT22** [comment]
@troy7615 Could you see if everything is ok now? @Omay238 helped me
https://editor.sprig.hackclub.com/?id=d0153cccc0ac975f565a17a1afb4ce64

**Comment by troy7615** [comment]
> @troy7615 Could you see if everything is ok now? @Omay238 helped me https://editor.sprig.hackclub.com/?id=d0153cccc0ac975f565a17a1afb4ce64
Looks Great! no more issues with the UFO movement, and there aren't errors at the end. Thanks!

**Comment by LucasHT22** [comment]
Ok!
