### ISSUE TITLE
Moving doesn't work on sprig for certain games

### ISSUE THREAD

**Issue by apzzd** [hackclub/sprig#698]
Hi! 

I just recently received and assembled my Sprig, and tried a few games on it. It worked fine - but when I tried to play the following game (Worldcraft, a game I made):

[https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/Worldcraft.js](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/Worldcraft.js)

I wasn't able to use the buttons. I then re-uploaded a game that I had tried before, and it worked perfectly. 

Just to make sure, I played Worldcraft in the browser using the online editor, and it worked.

Why doesn't this game run on the Sprig?

**Comment by Omay238** [comment]
Worldcraft is a bit too complex to run on the sprig. It isn't nearly as powerful as a normal computer, and thus it can't run all games.

**Comment by apzzd** [comment]
Oh, ok. Sad 😢

**Comment by apzzd** [comment]
Do you know the maximum file size that the Sprig can run? Then I might be able to refactor my code to make it more succinct.

**Comment by apzzd** [comment]
Ok, thanks for your help!
