### ISSUE TITLE
Sprig editor issues

### ISSUE THREAD

**Issue by KnightOfTheRoundTable** [hackclub/sprig#716]
The Sprig editor doesn't seem to be working as it usually does. The code segments that usually collapse (like the bitmaps, maps, and tunes) won't and the keywords (bitmap, map and tune) that usually turn into buttons and allow access to the editors don't show up. This issue occurs on new and old projects and on my chromebook, my friend's chromebook and my phone, so I don't think the issue is with the project or device. If I've missed something please let me know.

**Comment by leomcelroy** [comment]
There seems to be something wrong with the parsing and syntax highlighting. Try adding a comment like // as the first line.

**Comment by KnightOfTheRoundTable** [comment]
Adding a comment didn't seem to do anything, but deleting the block comment (/* author and game name */) makes everything go back to normal. Also, anything above the block comment lines look fine.

**Comment by leomcelroy** [comment]
Should be fixed now!
