### ISSUE TITLE
Consider adding a button for challenges to "reset code" to starting position

### ISSUE THREAD

**Issue by zachlatta** [hackclub/sprig#72]
In the process of solving a challenge, sometimes you accidentally break the game and want to reset the challenge to its original code. Right now the user has to refresh the page, and then re-open the challenge to get back to the starting position.

Suggestion: What if we had a button that was only visible when you had a challenge open to reset the code to where the challenge started? It could be in the navbar area and say "reset code".

If we're not interested in this, please feel free to close this issue.

**Comment by leomcelroy** [comment]
We've rethought challenges with the overhaul for Sprig.
