### ISSUE TITLE
Sugguestion: Support setTimeout or setInterval

### ISSUE THREAD

**Issue by sampyng** [hackclub/sprig#776]
Not sure if I did it wrong, but I found that `setTimeout()` or `setInterval()` don't have any effect. It would be great if either one of these functions is supported so time-based game or action game could be made without waiting for user inputs to update the screen.

**Comment by the456gamer** [comment]
both should work as normal. see Line 170
https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sprig_dodge.js

**Comment by grymmy** [comment]
I will attempt reproduction of this tomorrow.

**Comment by kognise** [comment]
Cannot reproduce. Please reopen if you can provide a game example where these don't work.

**Comment by sampyng** [comment]
Thanks. I just tried again with @the456gamer example and it works now. I believe I used a wrong syntax so the `setInterval` was not working. Sorry for the false alarm
