### ISSUE TITLE
Highlight errors in editor

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#797]

**Comment by alhardwarehyde** [comment]
@kognise I think this was moved over from linear- can you help clarify what this is so we can prioritize it?

**Comment by kognise** [comment]
In old Sprig the line number in the code editor was highlighted in red if an error occurred on that line.

**Comment by SamDev-7** [comment]
I'm trying to attempt this, I'll see what I can do.

**Comment by SamDev-7** [comment]
Similar to this, would it be good to add a JavaScript linter? Some could argue that one will learn more by figuring it out themselves, but a linter is certainly helpful if you know what you're doing.

**Comment by leomcelroy** [comment]
You could add a button to autoformat (which could be really helpful) but I'm strongly opposed to automatically changing the code beyond spacing/indentation. That behavior can be very confusing to beginners.

**Comment by kognise** [comment]
To me a linter feels against the spirit of Sprig. Even when building advanced things I think it's nice to not have a linter, just as there isn't autocomplete.

Formatter: maybe. Never seen a good autoconfigured formatter. Not strongly against, but care would need to be put into to make it good.

**Comment by leomcelroy** [comment]
Arduino and processing both include one I believe. In the P5 editor it's called "Tidy Code". https://editor.p5js.org/

**Comment by kognise** [comment]
Happy to have formatter if:

- It's never done automatically
- It doesn't touch semicolons or quote styles, only spacing
- Doesn't do weird line width normalization
- Isn't too prominent in interface

**Comment by alhardwarehyde** [comment]
@kognise does this mean this issue is good to close? Because it's moved to #976 ?

**Comment by alhardwarehyde** [comment]
@SamDev-7 is this something you're still working on?

**Comment by SamDev-7** [comment]
For this, nope. Everything is in that pr.
