### ISSUE TITLE
Update docs and pull request template

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#799]

**Comment by alhardwarehyde** [comment]
@kognise is this the issue to track updating all the references to outdated Sprig UI? Which docs? and what is being added?

**Comment by LucasHT22** [comment]
Hey, sorry to intrude, what would you change in the PR Template?

**Comment by grymmy** [comment]
@LucasHT22 Yup that's exactly what we're trying to find out here...

**Comment by LucasHT22** [comment]
Tbh, the current template is excellent (at least for us who are reviewing it), imo it doesn't need any changes

**Comment by SamDev-7** [comment]
Didn't GitHub introduce a new Pull Request Template UI? Maybe we can somehow try to use that?

**Comment by karamassie** [comment]
@SamDev-7 they have been updated , but if you want to make a new issue for the PR Template UI field, that'd be great!
