### ISSUE TITLE
Add function to check if any key is pressed & update reference docs

### ISSUE THREAD

**Issue by jessicard** [hackclub/sprig#80]
Right now I think you have to check specific keys. It would be nice if I could call a function in update that tells me if any key had been pressed. Let me know if this already exists!

**Comment by maxwofford** [comment]
This was added in https://github.com/hackclub/gamelab/pull/97/files#diff-e63b0c3236f1f8a88fe0106d222b6c75786e801c38d01534f7a1023e341ef096L689-R600, but documentation wasn't added to the reference docs. I'll update the issue to reflect that!

**Comment by maxwofford** [comment]
This shouldn't be closed until the reference docs shows how to use `e.pressedKey()` (no argument) and `e.pressedKey('AnyKey')`
<img width="655" alt="Screen Shot 2022-04-08 at 12 02 44" src="https://user-images.githubusercontent.com/5891442/162479776-66465d6f-4c91-4cde-a4be-7153ea1f57e2.png">

**Comment by cedric-h** [comment]
it's an interesting scenario. For example, imagine the illustrative character, billybob. billybob makes a game with a title screen in which one presses any key to continue.

He could iterate through all possible inputs, which are now limited to eight.

Billybob could also simply pick a single key, and accept that he will not be able to emulate this particular video game trope.

His case, we found, was worthy of considering, but not worth catering towards at the cost of additional API bloat.

WONTFIX
