### ISSUE TITLE
Add navbar active state

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#801]
On the main site pages it's currently somewhat difficult to tell what page you're on. The currently selected page link in the navbar item should have a different colored background from all the other items.

**Comment by grymmy** [comment]
@kognise Currently doesn't seem like this issue has enough information to be actionable.  Can more info be put in that would describe the proposed work?

**Comment by Shreeya-Rani** [comment]
Hey, I think I can do this. May I try?

**Comment by alhardwarehyde** [comment]
@Shreeya-Rani go for it!

**Comment by Shreeya-Rani** [comment]
Hey, I am assuming that all the necessary files are under the 'pages' folder only?

**Comment by alhardwarehyde** [comment]
@kognise is Shreeyas' above comment correct?

**Comment by kognise** [comment]
Nope, I think the `components` folder will be relevant as well.

**Comment by alhardwarehyde** [comment]
@Shreeya-Rani does that answer your question?

**Comment by ManishDait** [comment]
@alhardwarehyde , If this issue is still open can i work on it.
