### ISSUE TITLE
Social image for shared game is preview of game

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#803]

**Comment by alhardwarehyde** [comment]
@karamassie I believe this was one of your asks, can you clarify this ask?

**Comment by karamassie** [comment]
@kognise says this is not easy, so i'd just list it as nice to have. VERY LOW PRIO
The feature ask was that if I share a link of a game with someone (like in slack) the preview image that comes with it is the little preview image of my game , like we see in the gallery. 
This is easier to accomplish for games already in the gallery.

**Comment by karamassie** [comment]
very difficult to do, and would require rearchitecting.
