### ISSUE TITLE
Use Billy font in gallery

### ISSUE THREAD

**Issue by Omay238** [hackclub/sprig#819]

**Comment by Omay238** [comment]
It is just a better feel for Sprig in general. The Sprig has a similar font, so it should be similar throughout the site.

**Comment by grymmy** [comment]
@leomcelroy This is a product decision - should we accept this as a new feature request for prioritization?

**Comment by leomcelroy** [comment]
@kognise Can you show me how this looks?

**Comment by alhardwarehyde** [comment]
@kognise see Leo's ask above?

**Comment by kognise** [comment]
Sorry, and thanks for the reminder Al. Would look something like this. Feels like it obscures the content and is perhaps inconsistent with the rest of the site. Although I do kinda like how it's more unique than the Inter-only gallery. Billy is very bold for a copy font, although pretty for headers.

![](https://doggo.ninja/IByGCn.png)

**Comment by leomcelroy** [comment]
I agree with Lexi's commentary. Can we use it for the header and game titles? If you think that looks good Lexi let's do it. If not we can close this issue.

**Comment by kognise** [comment]
Frankly I just can't get it to look great. Don't think this is the best way to add flair. Maybe a different font.
