### ISSUE TITLE
After clicking "Delete" and closing menu "Are you sure?" persists.

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#824]
This should revert back to "Delete" if the menu is closed.

![Screen Shot 2023-02-22 at 1 09 53 PM](https://user-images.githubusercontent.com/27078897/220718272-ce8f14e7-0ee8-4d17-b9ff-0fd4c75998ed.png)

**Comment by kognise** [comment]
lol
![](https://doggo.ninja/yxBitz.png)
