### ISSUE TITLE
Add option to log out from editor.

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#827]

**Comment by kognise** [comment]
Why? Feels like this would inflate menus.

**Comment by leomcelroy** [comment]
It's functionality that will be very commonly used and it's too hidden at the moment. At many schools people share computers and have to return them after a usage session. At the moment it's not clear how to log out.

**Comment by jvm-cognition** [comment]
Can I hack at this?

**Comment by grymmy** [comment]
@jvm-cognition unassigned as you haven't replied, plz ping here if you'd like to take ownership of this issue

**Comment by Cosmin-Mare** [comment]
I'd like to tackle this as a first issue
