### ISSUE TITLE
Sprig beta feedback

### ISSUE THREAD

**Issue by Shrey-Mehra** [hackclub/sprig#834]
The website has some bugs-

1. Delay in the movement of the sprig console
2. improve in UI is needed**(the "Your Games" page is too blank and too edgy, you can try using rounded corners, the color scheme is good)**
3. The loading time of the gallery and game is slightly high

**Comment by kognise** [comment]
Thank you for your feedback! What do you mean by "delay in the movement of the sprig console"?

**Comment by SHREEYA2007** [comment]
Hey Kognise, the Sprig console in Home page is an moveable item, and the movement of it is slightly delayed, it probably could be because of delay in page loading in general but that is an issue.

**Comment by alhardwarehyde** [comment]
@Shrey-Mehra Thank you again for your feedback! There are 3 issues here, can you resubmit this as three different Github Issues?

Thanks!

**Comment by Shrey-Mehra** [comment]
Sure

**Comment by alhardwarehyde** [comment]
@Shrey-Mehra Thanks! Then I am closing this. If you feel this has been done in error reopen this issue
