### ISSUE TITLE
Suggested Change to Wording on Gallery Page

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#841]
Have a Sprig game to share with the community? Join the fun!  <<< This sounds vague and marketing-y when we need it clear. I'd make it just more functional like "Add your finished game to the Gallery" [button], likewise this line , "The best way to learn is by making things that you care about and sharing them with other people. Check out games by other Hack Clubbers!" I'd make it something like "We currently have (NUMBER) of games made my Hack Clubbers. Click on any to play it in the browser and see (and hack on!)  the code in our editor"

**Comment by alhardwarehyde** [comment]
Update Copy from:

"Have a Sprig game to share with the community? Join the fun!" to "Add your finished game to the Gallery" [button]"

"The best way to learn is by making things that you care about and sharing them with other people. Check out games by other Hack Clubbers!" to "We currently have (NUMBER) of games made my Hack Clubbers. Click on any to play it in the browser and see (and hack on!) the code in our editor"

**Comment by grymmy** [comment]
Self assigned on behalf of agentblack6k

**Comment by agentblack6000** [comment]
The PR is ready to merge!

**Comment by grymmy** [comment]
Closing issue on behalf of @agentblack6000, who, now having proper permissions, will be able to close their own issues from now on after getting their code merged.
