### ISSUE TITLE
UI Feedback: Tag List is Long, Utility unclear

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#842]
the tag list is long and many are meaningless

**Comment by alhardwarehyde** [comment]
@karamassie Which tags are at issue here and who is affected by it?

**Comment by karamassie** [comment]
@leomcelroy - would like your opinion on this.

**Comment by leomcelroy** [comment]
This is drawn from any tag provided in [metadata.json](https://github.com/hackclub/sprig/blob/main/games/metadata.json).

I agree only a few tags are particularly meaningful. Open to specific suggestions about how to improve but in absence of that I think it's fine as is.
