### ISSUE TITLE
Feedback(Kara): "Remix to save edits" wording is confusing

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#844]
"remix to save edits" <<< no clue what that means . the main verb is the problem... it is "remix" not "save", which is really confusing

**Comment by grymmy** [comment]
+1 this is confusing.

**Comment by LucasHT22** [comment]
remix reminds me https://scratch.mit.edu/

**Comment by grymmy** [comment]
TBH perhaps just a mousehover text on the button that explains what one would expect when they pressed it would remove confusion.

**Comment by leomcelroy** [comment]
Let's revisit if the users are confused. I'm going to close for now. I think this language is common with tools like ReplIt and Scratch.
