### ISSUE TITLE
Suggestion! Different Theme Options for Editor/Gallery

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#846]
i.e. first sprig page background as background for editor
![image (2)](https://user-images.githubusercontent.com/122998778/221036506-53ae0dec-1950-4acc-8622-12219ded082e.png)

**Comment by grymmy** [comment]
@leomcelroy Should we accept this as a feature request?

**Comment by leomcelroy** [comment]
I think we'll stick to one theme for the editor.
