### ISSUE TITLE
User can't tell they're in eraser mode in pixel editor

### ISSUE THREAD

**Issue by zachlatta** [hackclub/sprig#85]
Was working with @hackliv on Game Lab and they ran into a problem where they couldn't figure out why the draw tool wasn't working in the pixel editor:

![image](https://user-images.githubusercontent.com/992248/159966121-77926ecf-5065-46c0-9ac2-a0b2abc682ce.png)

The issue was that somehow the pixel editor got set to eraser mode, and they couldn't visually see it was in eraser mode. It wasn't clear that there was a portion of the pixel editor cut off to them either. I had to expand the pixel editor area because I knew that was possible.

![image](https://user-images.githubusercontent.com/992248/159966494-3c4542f6-4b8d-491f-a89f-138124f46a02.png)

**Comment by leomcelroy** [comment]
No longer relevant with the new Sprig system.
