### ISSUE TITLE
Error display hides horizontal scrollbar

### ISSUE THREAD

**Issue by the456gamer** [hackclub/sprig#855]
With error
![image](https://user-images.githubusercontent.com/42748092/221363095-b2daa5f5-5c02-420f-a4df-4782f324220c.png)
Without error
![image](https://user-images.githubusercontent.com/42748092/221363106-bdd1c699-5cf5-437a-94ec-0263c6634993.png)

in V1
![image](https://user-images.githubusercontent.com/42748092/221363184-19b3935d-a67b-4152-9105-56070c6fc122.png)

**Comment by kognise** [comment]
Thank you! Fixed in 168ba30.
