### ISSUE TITLE
no way to make emulator smaller / hidden [Sprig v2]

### ISSUE THREAD

**Issue by the456gamer** [hackclub/sprig#856]
v1 for comparison
![image](https://user-images.githubusercontent.com/42748092/221363337-c53e279d-ecd0-47a4-8381-c906817d12bd.png)

v2, where this is the smallest i can drag it
![image](https://user-images.githubusercontent.com/42748092/221363382-6f973198-6a9f-46c4-9c3c-c7f4d9d45d06.png)

suggested fix:
a method of hiding the code editor, or the emulator at the same time, and maybe reducing the minimum size a bit

**Comment by alhardwarehyde** [comment]
The ask here is:

on the right side of text editor you can drag a widget to change the size of the editor.

in the old UI you can drag it fully to the right (hiding the emulator)

The ask is for the new UI to do the same.

**Comment by kognise** [comment]
I don't really think this is an important feature, closing this for now although open to more feedback.
