### ISSUE TITLE
Add Captcha to Email Submission (spam deterrent)

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#863]

**Comment by grymmy** [comment]
There seems to still be an issue here.  Where was the captcha implemented?  Right now, there is no verification of humanity between entering your email address and data being saved when following these instructions (and step #6 cannot be performed).
Steps to reproduce:
1. Ensure you are NOT logged into https://sprig-beta.hackclub.dev
2. Navigate to https://sprig-beta.hackclub.dev/gallery
3. Click on a random Hack Clubber's game.4. 
4. Click 'Remix to save edits'
5. Enter your email address.
6. Fill in the captcha
7. Wait for the editor to autosave.
8. Close your browser window.

Expected result: A new game should show up in "Your Games".  The content of the new game should be exactly the same as the game you remixed.  An email should be received stating that a new game has been added to "Your games".  A captcha should appear before logging in.

**Comment by grymmy** [comment]
Per my understanding with @kognise, this is expected behavior as we're using invisible captchas.  It is nontrivial to test this scenario.  Closing this issue as fixed.
