### ISSUE TITLE
Produce new updated content to be linked to from the "Help" section of the v2 Sprig editor

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#870]

**Comment by grymmy** [comment]
@alhardwarehyde Hmm do we know who is going to produce these?  Perhaps this should be split into two issues too...

**Comment by grymmy** [comment]
FYI - the scope of this issue is to produce the new content.  @cjdenio if you could put the links to the content here, we will track the modification to the help window links code as a separate issue.

**Comment by karamassie** [comment]
pinging this for update :p

**Comment by LucasHT22** [comment]
Hey! do you have any updates?

**Comment by alhardwarehyde** [comment]
@LucasHT22 we have the video, what's the best way to get the video to you for updating?

**Comment by LucasHT22** [comment]
hosted on youtube as an unlisted video would be great (just like the previous videos)

**Comment by alhardwarehyde** [comment]
Video hosted! Closing this out! https://www.youtube.com/watch?v=ZOPYB6dw4Os
