### ISSUE TITLE
Game Player looks weird on Mobile when in Portrait Mode

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#873]
It would be really nice if the browser screen was locked to widescreen orientation (MOBILE ONLY).

**Comment by kognise** [comment]
I'm pretty sure this is already implemented? Is this not the behavior you're seeing?

**Comment by alhardwarehyde** [comment]
@kognise we just tested this on Graham's phone. 

It locks to widescreen but there is some weird behavior on a Samsung Galaxy S23

**Comment by kognise** [comment]
What "weird behavior"?

**Comment by kognise** [comment]
Ah, I'm gonna close this as a wontfix. This behavior is the same as old Sprig, we discussed this, and concluded it's okay.

**Comment by grymmy** [comment]
@kognise just to be clear, there is no trivial fix to completely disable rotation entirely and just solve the bug?  This is a technical limitation that is insurmountable?

**Comment by kognise** [comment]
I'm pretty sure the alternative is layout shifting which is more annoying to users. Although maybe we should be rethinking the whole mobile experience.

**Comment by kognise** [comment]
And yes, as far as I know you can't just lock orientation if you're not fullscreen or a PWA.

**Comment by grymmy** [comment]
> And yes, as far as I know you can't just lock orientation if you're not fullscreen or a PWA
👌
