### ISSUE TITLE
Make autosaving errors more visible and annoying

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#874]
Right now there is no contrast to the error messages that occur when autosaving fails in the new editor, and they look too similar to successful saves (same color, etc).  Given this can cause data loss, I suggest changing the font to red (or use some other method of gaining someones' attention) to warn the user.

**Comment by kognise** [comment]
I made it blink, do you think this is intrusive enough?

**Comment by grymmy** [comment]
Yeah that'd be better!
