### ISSUE TITLE
wrong url: platform_rogue in Main Page

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#875]

**Comment by alhardwarehyde** [comment]
@LucasHT22 What is the wrong link? And where is it exactly?

**Comment by LucasHT22** [comment]
![image](https://user-images.githubusercontent.com/88567622/222783484-63029c3b-61ce-44eb-a51d-4605c3a54ad5.png)
it's a small error: it's https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/platform_rogue.js not
https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/playform_rogue.js (pla`t`form not pla`y`form)
