### ISSUE TITLE
Migration doesn't work on Firefox and Safari

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#885]
Chrome and Edge seem to support migration fine, but Firefox and Safari fail to show games for migration.

**Comment by alhardwarehyde** [comment]
@grymmy can you provide more context? Repro steps and the proposed solution we came up with yesterday?

**Comment by grymmy** [comment]
@alhardwarehyde  FYI - https://docs.google.com/spreadsheets/d/1mYspi4uSjdPdT8B_M1FlEK-IhTQ0GvHwbDB1NSeUMyw/edit#gid=1444670267 test case #10
