### ISSUE TITLE
while loops crashing firefox tab

### ISSUE THREAD

**Issue by Patcybermind** [hackclub/sprig#890]
![image](https://user-images.githubusercontent.com/97562509/222488708-87fd411e-dc94-4156-b986-1a851b54b53b.png)
this is what i see after it crashes the tab

**Comment by Patcybermind** [comment]
how do i put the sprig 2.0 tag?

**Comment by kognise** [comment]
Pretty sure this has always been an issue and isn't a Sprig 2.0 thing. In general if you have an infinite loop in JS code it'll crash the tab.

**Comment by Patcybermind** [comment]
and I tought it was like python

**Comment by alhardwarehyde** [comment]
Thanks for your feedback because we can't fix this I am closing this one out.
