### ISSUE TITLE
captcha overlaps help button

### ISSUE THREAD

**Issue by the456gamer** [hackclub/sprig#892]
![image](https://user-images.githubusercontent.com/42748092/222603961-ceb52546-5fa0-42d0-b4eb-c730b0c62a77.png)

**Comment by alhardwarehyde** [comment]
@the456gamer do you have a suggestion for where the Captcha and Help Button should be?

**Comment by the456gamer** [comment]
https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed
