### ISSUE TITLE
Feature to correct email if entered wrong

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#898]

**Comment by kognise** [comment]
Currently if you typo your email during the save flow there's no easy way to go back and correct it without going and making a new game (and maybe clearing your cookies?)

Possibly adding a logout button in the editor like @leomcelroy suggested could help this.

**Comment by alhardwarehyde** [comment]
So I understand, the feature is: if I enter the wrong email I can edit my email somewhere?

**Comment by sonicx180** [comment]
May i assign my self to this?

**Comment by sonicx180** [comment]
Wait, isn't this already a feature, because when you login and click send code, it gives you an option to go back, see below.
![image](https://github.com/hackclub/sprig/assets/83236320/f3c94027-0744-4642-bda6-05a882dcd07f)
