### ISSUE TITLE
Canvas background should not be white

### ISSUE THREAD

**Issue by Vidhaaaaaa** [hackclub/sprig#903]
I found out that there is a white/transparent margin on both sides of the grid on the canvas, and it merges with the grid background if we don't have a sprite as the background, it would be better if there will be some kind of a thin border with it!

NOTES (by @kognise):

I propose just changing the background to `accent-dark` or black (like the Sprig display) to make the screen area not blend in with the background.

**Comment by alhardwarehyde** [comment]
@leomcelroy should we do this?

**Comment by leomcelroy** [comment]
I was discussing this with Lexi yesterday. There should certainly be some visual cue to differentiate the canvas from the background.

**Comment by grymmy** [comment]
> can someone clarify further what exactly we need to do?

Add a small contrasting border surrounding the game viewport is my understanding.

**Comment by leomcelroy** [comment]
The real issue is differentiating the canvas from the background. Changing background colors would also serve this purpose and is what Lexi intends to implement.
