### ISSUE TITLE
Undo/Redo click twice for last stroke to get removed/added back again

### ISSUE THREAD

**Issue by Vidhaaaaaa** [hackclub/sprig#904]
we have to click / ctrl + z / Cmd + z  twice to undo the last stroke on the bitmap and the same as for redo.

**Comment by alhardwarehyde** [comment]
@leomcelroy should we do this?

**Comment by leomcelroy** [comment]
Is this bug reproducible?

**Comment by kognise** [comment]
@grymmy could you please work on reproducing this? Thanks so much!

**Comment by kognise** [comment]
@Vidhaaaaaa I can't reproduce this, I only need to click undo/redo once. If you're still having this issue, could you please add steps to triggering the issue?

**Comment by Vidhaaaaaa** [comment]
I still get this issue, if i put a stroke, and if i want to remove it, i **_have_** to click undo twice, and the same as for redo.
