### ISSUE TITLE
Add clear button to sound editor

### ISSUE THREAD

**Issue by mesaumya** [hackclub/sprig#905]
As I was trying Sprig the first time, it was a little difficult for me to figure out how to clear the engine out until I understood the concept of right-click, also I think it would be easier for the user if there will be an option to clear the engine and the sequencer with one click/button somewhere

**Comment by alhardwarehyde** [comment]
@mesaumya Thank you for your feedback! Do you have a suggestion of where the button should go?

**Comment by grymmy** [comment]
@leomcelroy do you support implementation of this feature?

**Comment by leomcelroy** [comment]
I support this.
