### ISSUE TITLE
Make sure to retain support for non-qwerty keyboards

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#913]
We need to ensure that code submitted in PR https://github.com/hackclub/sprig/pull/547 gets merged into the new branch and/or is not lost when we do the merge.

**Comment by leomcelroy** [comment]
We should do this with an options panel where the user can specify key mappings so defaults are always the same and to support other types of keyboards that aren't suited by whatever default choice we might make.

**Comment by grymmy** [comment]
Closing this issue in preference of implementing https://github.com/orgs/hackclub/projects/32/views/1?pane=issue&itemId=22278013 as @leomcelroy suggested.
