### ISSUE TITLE
Add new options menu to allow for rebinding key bindings

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#915]
The web editor should allow for changing the keybindings arbitrarily via a user interface available from an options panel.  See https://github.com/hackclub/sprig/pull/547/files for legacy discussions on this issue.

**Comment by alhardwarehyde** [comment]
@leomcelroy is this something we want to do?

**Comment by kognise** [comment]
Propose also using the [Keyboard.getLayoutMap](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap) API and putting copy somewhere on the interface indicating alternate keyboard mappings on non-QWERTY keyboards.

**Comment by leomcelroy** [comment]
Yes let's do this. I would implement similar to how B originally proposed but make it configurable.

**Comment by Arpan-206** [comment]
I'm volunteering to work on this issue.

**Comment by DevIos01** [comment]
merged and live at https://sprig.hackclub.com
