### ISSUE TITLE
Update "Help" window links to newly produced content

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#917]
There are links at the top of the "Help" section in the new v2 editor that reference the old sprig UI.  Update the links to the newly produced content.

**Comment by grymmy** [comment]
Content will become available upon completion of https://github.com/orgs/hackclub/projects/32/views/1?pane=issue&itemId=21680223.

**Comment by alhardwarehyde** [comment]
#870

**Comment by grymmy** [comment]
@LucasHT22 you are the current assignee here, is there work yet to be finished here, or can this be closed?

**Comment by alhardwarehyde** [comment]
@LucasHT22 video up: https://www.youtube.com/watch?v=ZOPYB6dw4Os
