### ISSUE TITLE
Make login flows consistent and not require email confirmation

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#920]
Notes from @zachlatta:

```
Some users aren't going to be logged into their Google accounts since they are on school computers, so they're not going to be able to receive the login code without logging into Google first - which can be a huge pain, especially because of 2 factor auth. This is a use case I talked through with Leo and Lexi. There is a specific student I'm thinking of that I helped out at the Charlotte coding club that could not get into their Google account on the computer they using, so they couldn't email their Sprig game to themselves. Then they lost all their progress.

I know this new interface has a "use Sprig without saving flow", but I don't think in the context of a club meeting they would probably opt for it. I think the most likely flow they would go through is:

Go to Sprig editor
See they need to get a login code to save their work
Put their email in
Spend the next 10 minutes trying to log into Google account and struggling
```
My $0.02 is that I am aware there are two distinct login flows, one requiring email verification (login from main page), and one that doesn't (remix game).  To me, this inconsistency has felt very strange.

While this bug is triaged/prioritized/defined, please add commentary to this issue to make it crystal clear how exactly all login UX should function and get product signoff on the exact approach.

**Comment by alhardwarehyde** [comment]
@leomcelroy can you add comments to this?

**Comment by leomcelroy** [comment]
User's don't have to log-in to use and save games in the editor. What I think could be clarified more is that it tells you your are not logged in if it just has an email even if it is saving games. It does this because you can't read games from an account without verifying it. The overall behavior is as you request though.
