### ISSUE TITLE
Make migration page show automagically

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#921]
Feedback from @zachlatta:

`The migration page call to action is too small, and in the bottom left. IMO it should be the page you go to immediately after you log in if you have games detected in old system.`

When triaging this issue, please add commentary about how exactly what the criteria for auto-navigation to the migration page will be.

**Comment by alhardwarehyde** [comment]
@leomcelroy can you post comments?

**Comment by leomcelroy** [comment]
I thought this was the case? In what scenarios does this occur @kognise

**Comment by kognise** [comment]
I believe Zach is suggesting we make the CTA much more prominent (or a redirect).

**Comment by leomcelroy** [comment]
It shouldn't be a redirect because you may have migrated games already and they are still in the old system. What do we do now to detect if it's your first log-in. That's the only time it should redirect. And in that case I think a pop-up is still preferable.

**Comment by grymmy** [comment]
I am closing this as @leomcelroy seems to have made a product decision re: this feature request.
