### ISSUE TITLE
First-use experience - tutorial drop-in

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#925]
Feedback from @zachlatta:

`On my first game that I make, I want to immediately be dropped into the Sprig tutorial. I had to search in the interface to figure out where the tutorial was.`

During triage, and prior to implementation, please define exactly what criteria will be used to determine when to drop the users into a tutorial by default.

**Comment by alhardwarehyde** [comment]
@leomcelroy can you add commentary?

**Comment by leomcelroy** [comment]
We link to the tutorial in the top of the default document now.
