### ISSUE TITLE
change text on "your games" button

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#926]
Feedback from @zachlatta:

Needs a stronger call to action. Right now the main call to action is "Your games" button when you're logged in on the homepage. But I haven't made any games yet! When not logged in, it's "Get started"

I want a call to action that 1) inspires me from what other people have made, and 2) gets me very quickly started building my own games and understanding the capabilities of the engine.

**Comment by alhardwarehyde** [comment]
@leomcelroy Should we do this?

**Comment by leomcelroy** [comment]
We should change the copy in this button to address this.

![Image](https://user-images.githubusercontent.com/27078897/225367402-470af8ef-ea4c-4fbc-8270-527893f8d390.png)

@kognise any suggestions?

Maybe just "Get Started"

**Comment by kognise** [comment]
Agree. Get started, should go to new game page instead of your games list. This is a pretty easy change to make.
