### ISSUE TITLE
Provide "call to action" for new sprig users who haven't made a game yet

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#927]
Feedback from @zachlatta:
`I want a call to action that 1) inspires me from what other people have made, and 2) gets me very quickly started building my own games and understanding the capabilities of the engine.`

During triage and prior to implementation, please ensure we define and comment here exactly what this call to action will be and how it should function.

**Comment by alhardwarehyde** [comment]
@kognise do you have ideas on what to do with this feedback?

**Comment by leomcelroy** [comment]
This is redundant with #926
