### ISSUE TITLE
Why does open editor lead to this page after migrating games?

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#932]
![Screen Shot 2023-03-08 at 12 09 28 PM](https://user-images.githubusercontent.com/27078897/223781696-9814b2d4-6f40-4a3f-9492-7598276168ca.png)

**Comment by leomcelroy** [comment]
This is a major bug. I can't get to the editor without logging in.

Solving this is making the link do what it should always do. Go to the editor.

**Comment by kognise** [comment]
I can't seem to reproduce this in any permutation.

**Comment by leomcelroy** [comment]
I'll mark it as low prio if it can't be reproduced now.

**Comment by grymmy** [comment]
I am closing this issue due to lack of ability to reproduce and inactivity - if it was serious it would have needed to be addressed by now.  Please re-open if you want to advocate for this issue...
