### ISSUE TITLE
Why does this change from a text link to a logo?

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#935]
![Screen Shot 2023-03-08 at 12 29 07 PM](https://user-images.githubusercontent.com/27078897/223786396-0af98961-b24f-414c-b3e7-a9c3d81c3243.png)

**Comment by alhardwarehyde** [comment]
@leomcelroy so I understand the issue is the new game changes from a text link to a logo? When does that happen? I am having a hard time duplicating it.

**Comment by leomcelroy** [comment]
When not logged in on the main page it is written in text.

**Comment by LucasHT22** [comment]
When you are not logged in, it appears written because some people were thinking that the login was done via GitHub due to the proximity to the login button

**Comment by leomcelroy** [comment]
Alright.
