### ISSUE TITLE
No option to make a new game when not logged in?

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#938]
You already have my email so I should be able to write games to the account.

![Screen Shot 2023-03-08 at 12 41 57 PM](https://user-images.githubusercontent.com/27078897/223789459-bc96c898-18bb-45e3-b5f7-861067b78bed.png)

**Comment by leomcelroy** [comment]
Yes! And even if you aren't logged in you should still be able to clear the current file with a blank one.

**Comment by kognise** [comment]
I propose we add a "reset editor" button or something in that menu that resets the editor to the template game. This can be in the place where the new game button normally is, or somewhere else. Whatever makes sense hierarchically.

**Comment by leomcelroy** [comment]
That's basically what I wanted the new game button to be. Sounds good. What is the need for new game with it?
