### ISSUE TITLE
Do error reporting pass

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#972]
Go through the engine codebase and identify locations where error messages could be added, and add them.

Example: `setMap({})` should probably have a custom error message. Other common typing mishaps as well.

**Comment by snoglobe** [comment]
I was thinking also doing trivial errors like `x is not defined` because the `at anonymous (index.5322f59a.js:48:3)` was scaring some people in my club. I'll look for some errors now!

**Comment by snoglobe** [comment]
Another thing: checking that the keys of `setPushable` are all objects.
