### ISSUE TITLE
Create a release management strategy and associated runbook

### ISSUE THREAD

**Issue by grymmy** [hackclub/sprig#973]
Per discussion in #970 with @leomcelroy and myself, we should define a release management strategy that looks something like this:

1) At some cadence, we tag the 'main' branch with a version.  This becomes a 'candidate for production'.
2) When release candidates gets tagged, they should deploy to a staging (testing) environment.
3) When we feel it is appropriate, tagged and tested releases get deployed to production.

This does mean that we will move away from immediately pushing code that's landed to the 'main' branch to production.

**Comment by kognise** [comment]
Haven't been following your conversation with Leo but I just skimmed it. I think more checks that block merging into main would be very good, but also believe this would solve the major issues. I am, however, not convinced a staging environment and release schedule is necessary or even a good thing.

The cost is significantly increased friction and time to deployment for all changes, and the benefit (if PR checks are in place) is unclear to me. Vercel deploys a preview of every PR. I don't think we will be pushing out huge amounts of updates, so I'm under the impression that testing these previews is sufficient.

What problem do you think a staging environment solves that isn't already solved by PR preview environments?

**Comment by grymmy** [comment]
The problem that a staging environment and release strategy solves is that helps us to avoid shipping problematic code inadvertently landed to main to our users.  As you stated yourself, vercel deploys a preview immediately upon sending out a PR, so even with a staging environment, it doesn't slow down developers in running their own tests of their own PRs (perhaps the most important one being can it even deploy in vercel at all).  It is not reasonable, however, to expect that our developers write their code perfectly and have done robust testing for every PR they author.

Having a release strategy, cutting a build off of 'main' at some cadence, allows for maintaining steady state on production code.  It also allows the team to know exactly when things change on production, because deployments become well-communicated and coordinated.  This alone is very valuable, even if you don't have a staging environment.  It becomes even more effective in protecting our users when we have a staging environment that testers can bang on prior to promoting a candidate build to production.  It allows for release notes to be generated (consistently and always) so our users can know what new features are present and what bugs are fixed.

I do agree that there are certain things we might want to consider deploying at a faster cadence, such as games themselves - but even those I question the real need for them being shipped to prod quickly.  Would there by riots, having to wait a few days before your landed game hits the gallery?  I kind of doubt it.

**Comment by grymmy** [comment]
Another thing - nothing would stop any person with access to do the prod deploy themselves - but if you do it outside of schedule, you should be responsible for the deploy and the process that goes along with it, which would ideally be script-supported.

**Comment by kognise** [comment]
> The problem that a staging environment and release strategy solves is that helps us to avoid shipping problematic code inadvertently landed to main to our users. As you stated yourself, vercel deploys a preview immediately upon sending out a PR, so even with a staging environment, it doesn't slow down developers in running their own tests of their own PRs (perhaps the most important one being can it even deploy in vercel at all). It is not reasonable, however, to expect that our developers write their code perfectly and have done robust testing for every PR they author.

I apologize if I'm misunderstanding, but I don't think this accounts for the possibility of having a good review process before landing PRs in main. It's not like anyone can merge— we can require reviews from code owners, passing tests, etc. and enforce this with GitHub branch protection rules. I'm not saying we should expect all developers to write perfect code, I'm suggesting we do testing at the PR level and we make merge the marker of valid+tested+trusted code. IMO this makes more sense for the pace of this project than a system where that marker is a tagged release; especially with the infrequency of PRs I think it's less cumbersome and easier to grok.

**Comment by kognise** [comment]
> it may be extremely difficult in practice to do sufficient and reasonable testing on each individual PR to prevent issues for our users

I'm curious why you think it's extremely difficult to do sufficient testing on individual PRs, but it's easier when those same changes are deployed somewhere different?

> it doesn't seem like we currently have a robust code review process

This is probably true; if so, it would be preferable to develop one. But I believe this is equally necessary whether we go with my proposed strategy or yours.

> I have never worked on a larger distributed team project where things landed to the main branch were immediately trustable as production-ready without having robust automated test coverage.

With all due respect, what makes sense for Sprig may be different from what made sense for these highly critical, frequently deployed, and large team projects you've worked on.

> Asking PR authors to run an entire test plan for each change they make, for instance, just doesn't scale...

I don't think I was suggesting this. If the bar for production *really* is running an entire test plan (I'm not sure this is actually necessary or a good idea) then that should be a required check before merge.

**Comment by grymmy** [comment]
> I'm curious why you think it's extremely difficult to do sufficient testing on individual PRs
I think it boils down to people being imperfect + a dose of human nature.  Innocuous-looking changes can often have unintended and potentially dramatic effects.

> With all due respect, what makes sense for Sprig may be different from what made sense for these highly critical, frequently deployed, and large team projects you've worked on.
I think we all need to get on the same page re: stability and reliability.  My personal opinion is that if there are reasonable things we can do to make our users' experience more stable and more predictable, it is a good thing, and can also assist in growing the userbase more quickly.  I also would stress that it serves more purpose than just that, too - it would then allow us to be more conscious about when and how our production changes.

> If the bar for production really is running an entire test plan
It could be, and arguably should be.  In the past, one way I've seen this realized in a reasonable manner is to have both a comprehensive, and also a separate sanity/release test plan.  Depending on changes that've occurred in some period, one could be used as opposed to another to be more efficient.  A sanity plan would be a subset of the entire plan and cover things like "all pages are renderable" and other quickly-testable things.  It would also then be a good starting point to replace with integration tests.

**Comment by kognise** [comment]
> I think it boils down to people being imperfect + a dose of human nature. Innocuous-looking changes can often have unintended and potentially dramatic effects.

Yes. Completely ignoring tolerances around this, ***we can use merge checks and a PR review process to catch things***. Wherever our thresholds are.

> I think we all need to get on the same page re: stability and reliability.

I agree. I also think this isn't tightly coupled to this discussion about deployment and should be taken elsewhere. I agree with your thoughts on this for the most part!

**Comment by kognise** [comment]
Just to reiterate, my concern is purely about having a staging environment and tagged release system as opposed to PRs being the point of safety checks.

**Comment by maxwofford** [comment]
It looks like this is a stale discussion. Based on the postmortem from recent outage[^1] I'd like to propose the following:

- We officially adopt [SemVar](https://semver.org/)
  - Any database/schema change is at least considered a minor update
  - Our game plan doc for handling downtime includes a line like "rollback to an earlier patch of the same minor version that's deployed"
- We bump sprig to 1.0 to indicate...
  - Sprig is on a stable major release
  - Sprig is LTS
  - Reverts to tagged versions before 1.0 may not respect the current requirements on versioning
  
I hear the discussion above about how to roll out a release management strategy and I think there's a valid open discussion above, but that shouldn't block us from setting standards on our versioning and prevent releases. It would have been helpful to know how far back I can safely roll back production in this weekend's outage and the current tagging system didn't provide that experience for me.

[^1]: @grymmy, can I link to that publicly, or should that be an internal doc?

**Comment by grymmy** [comment]
Closing this as separate discussions have been had recently that deserve a separate, clean issue tracking what we plan on doing.
