### ISSUE TITLE
Add built-in autoformatting tool

### ISSUE THREAD

**Issue by kognise** [hackclub/sprig#976]
The editor should maybe have a tool to tidy up the code's indentation and such.

Requirements:

- It's never done automatically
- It doesn't touch semicolons or quote styles, only spacing
- Doesn't do weird line width normalization
- Isn't too prominent in interface
- It intuits indentation style?

I love the "tidy code" wording that the P5 editor uses!

**Comment by gptkrsh** [comment]
Can I work on this issue?

**Comment by alhardwarehyde** [comment]
@gptkrsh sorry for the delay response, go for it!

**Comment by grymmy** [comment]
Closing this as not planned - if anything I think the platform code itself would benefit from additional linting/etc, not sprig games...  @leomcelroy be aware I am axing this, if you feel strongly about it and want to advocate for its existence plz reopen & ping me...
