### ISSUE TITLE
The link to the tutorial doesn't work

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#989]
When I click the link to pen the tutorial it brings me to my games.

![Screen Recording 2023-03-27 at 1 49 19 PM](https://user-images.githubusercontent.com/27078897/228024994-1c3b4f89-99d3-4b4c-8050-94633403b056.gif)

**Comment by kognise** [comment]
Good catch, it's linking to sprig.hackclub.dev rather than sprig.hackclub.com. I'll do a full repo search for old links that I somehow missed (I thought I did this before!)
