### ISSUE TITLE
Newcomers still not noticing HELP tab 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#992]
Feedback from a recent hackathon sprig workshop is that newcomers to the editor still aren't finding our HELP menu. 
Suggestion to fix is to have it auto-open if you're in the Getting Started workshop (which is where most newcomers would be).

**Comment by kognise** [comment]
It auto-opens the first time you open the editor, always.

**Comment by Tiger-The-Cat** [comment]
Maybe some sort of popup that points to the help screen for the first time?

**Comment by SamDev-7** [comment]
Already implemented since the addition of tutorials from #1081. [Link to code in question](https://github.com/hackclub/sprig/pull/1081/files#diff-eaab6a794eac86ba636e60be1175741e692770d339eacf09f9d38abe81cbd489R17).
